-- AEGIS_OEE Full Procedure DDL Extraction Script
-- Run each SELECT to get the full CREATE OR REPLACE PROCEDURE statement
-- Generated: 2026-10-06

-- ACTION schema procedures
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.SCORE_ALERTS()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.GET_ASSET_EVIDENCE(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.PROPOSE_WORK_ORDER(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.CREATE_WORK_ORDER(VARCHAR, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.CHECK_PARTS(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.START_WORK_ORDER(VARCHAR, VARCHAR, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.COMPLETE_WORK_ORDER(VARCHAR, VARCHAR, VARCHAR, VARCHAR, FLOAT, VARIANT, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.CLOSE_WORK_ORDER(VARCHAR, VARCHAR, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.UPDATE_REQUISITION_STATUS(VARCHAR, VARCHAR, VARCHAR, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.PROPOSE_SCHEDULE(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.AUTO_SCHEDULE_WO(VARCHAR, VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.SCHEDULE_WORK_ORDER(VARCHAR, VARCHAR, VARCHAR, BOOLEAN)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.RETRY_OUTBOX()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.QUEUE_GITHUB_SYNC(VARCHAR)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.NOTIFY_SLACK(VARIANT)');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ACTION.ENRICH_OUTBOX_WITH_SCHEDULE(VARCHAR)');

-- ML schema procedures
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ML.DETECT_ANOMALIES()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ML.DETECT_ANOMALIES_BACKFILL()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ML.DETECT_ZSCORE_ANOMALIES()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ML.DETECT_ZSCORE_ANOMALIES_BACKFILL()');
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.ML.TEST_PROC()');

-- CORE schema procedures
SELECT GET_DDL('PROCEDURE', 'AEGIS_OEE.CORE.REFRESH_CMMS_PLAN()');

-- UDF
SELECT GET_DDL('FUNCTION', 'AEGIS_OEE.ACTION.GET_EST_DURATION_MIN(VARCHAR, VARCHAR)');

-- Views
SELECT GET_DDL('VIEW', 'AEGIS_OEE.ML.V_TRAIN_VIB_HEALTHY');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.ML.V_TRAIN_TEMP_HEALTHY');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.ML.V_TRAIN_RPM_HEALTHY');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.ML.V_VIB_HOURLY');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.ML.V_OEE_DAILY');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.SEMANTIC.V_MTBF_MTTR');
SELECT GET_DDL('VIEW', 'AEGIS_OEE.SEMANTIC.V_SIX_BIG_LOSSES');

-- Semantic View
SELECT GET_DDL('SEMANTIC VIEW', 'AEGIS_OEE.SEMANTIC.MANUFACTURING_OPERATIONS');

-- Agent
SELECT GET_DDL('CORTEX AGENT', 'AEGIS_OEE.ACTION.AEGIS_RCA_AGENT');

-- Search Service
DESCRIBE CORTEX SEARCH SERVICE AEGIS_OEE.SEMANTIC.MAINTENANCE_SEARCH;

-- Dynamic Tables
SHOW DYNAMIC TABLES IN DATABASE AEGIS_OEE;
