-- =============================================================================
-- demo_reset.sql — Restore pristine demo state for AegisOEE
-- Run via: snow sql -f scripts/demo_reset.sql --connection <conn>
-- =============================================================================
USE DATABASE AEGIS_OEE;
USE WAREHOUSE AEGIS_WH;

-- 1. Truncate ACTION tables
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.ALERT;
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.WORK_ORDER;
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX;
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.PURCHASE_REQUISITION;
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.WO_SCHEDULE;
TRUNCATE TABLE IF EXISTS AEGIS_OEE.ACTION.ACTION_AUDIT;

-- 2. Reset PARTS_INVENTORY to seed values
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 1,  RESERVED_QTY = 0 WHERE PART_ID = 'P001';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 12, RESERVED_QTY = 2 WHERE PART_ID = 'P002';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 6,  RESERVED_QTY = 0 WHERE PART_ID = 'P003';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 3,  RESERVED_QTY = 0 WHERE PART_ID = 'P004';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 5,  RESERVED_QTY = 1 WHERE PART_ID = 'P005';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 8,  RESERVED_QTY = 0 WHERE PART_ID = 'P006';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 15, RESERVED_QTY = 0 WHERE PART_ID = 'P007';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 4,  RESERVED_QTY = 0 WHERE PART_ID = 'P008';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 6,  RESERVED_QTY = 0 WHERE PART_ID = 'P009';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 3,  RESERVED_QTY = 0 WHERE PART_ID = 'P010';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 4,  RESERVED_QTY = 0 WHERE PART_ID = 'P011';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 5,  RESERVED_QTY = 0 WHERE PART_ID = 'P012';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 10, RESERVED_QTY = 0 WHERE PART_ID = 'P013';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 3,  RESERVED_QTY = 0 WHERE PART_ID = 'P014';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 8,  RESERVED_QTY = 0 WHERE PART_ID = 'P015';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 3,  RESERVED_QTY = 0 WHERE PART_ID = 'P016';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 2,  RESERVED_QTY = 0 WHERE PART_ID = 'P017';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 20, RESERVED_QTY = 0 WHERE PART_ID = 'P018';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 10, RESERVED_QTY = 0 WHERE PART_ID = 'P019';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 4,  RESERVED_QTY = 0 WHERE PART_ID = 'P020';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 4,  RESERVED_QTY = 0 WHERE PART_ID = 'P021';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 15, RESERVED_QTY = 0 WHERE PART_ID = 'P022';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 6,  RESERVED_QTY = 0 WHERE PART_ID = 'P023';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 2,  RESERVED_QTY = 0 WHERE PART_ID = 'P024';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 5,  RESERVED_QTY = 0 WHERE PART_ID = 'P025';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 6,  RESERVED_QTY = 0 WHERE PART_ID = 'P026';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 8,  RESERVED_QTY = 0 WHERE PART_ID = 'P027';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 5,  RESERVED_QTY = 0 WHERE PART_ID = 'P028';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 3,  RESERVED_QTY = 0 WHERE PART_ID = 'P029';
UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY SET ON_HAND_QTY = 1,  RESERVED_QTY = 0 WHERE PART_ID = 'P030';

-- 3. Reset MAINTENANCE_WINDOW bookings
UPDATE AEGIS_OEE.CORE.MAINTENANCE_WINDOW SET BOOKED_MIN = 0, STATUS = 'OPEN' WHERE STATUS = 'BOOKED';

-- 4. Refresh CMMS plan
CALL AEGIS_OEE.CORE.REFRESH_CMMS_PLAN();

-- 5. Delete today's injected telemetry (live-replay rows only)
DELETE FROM AEGIS_OEE.RAW.SENSOR_TELEMETRY WHERE INGEST_TS >= CURRENT_DATE();

-- 6. Delete today's ML anomaly events
DELETE FROM AEGIS_OEE.ML.ANOMALY_EVENTS WHERE TS >= CURRENT_DATE();

-- 7. Suspend all tasks
ALTER TASK IF EXISTS AEGIS_OEE.ML.TASK_DETECT_ANOMALIES SUSPEND;
ALTER TASK IF EXISTS AEGIS_OEE.ACTION.TASK_SCORE_ALERTS SUSPEND;
ALTER TASK IF EXISTS AEGIS_OEE.ACTION.TASK_OUTBOX_RETRY SUSPEND;
ALTER TASK IF EXISTS AEGIS_OEE.CORE.TASK_REFRESH_CMMS_PLAN SUSPEND;

-- 8. Insert DEMO_RESET audit row
INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT (AUDIT_ID, TS, ACTOR, ACTION, OBJECT_REF, DETAIL)
SELECT 'AUD_DEMO_RESET_' || TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISSFF3'),
       CURRENT_TIMESTAMP(), 'SYSTEM', 'DEMO_RESET', 'AEGIS_OEE',
       OBJECT_CONSTRUCT('reset_ts', CURRENT_TIMESTAMP()::STRING, 'method', 'demo_reset.sql');

-- 9. Verify
SELECT 'ALERT' AS TBL, COUNT(*) AS CNT FROM AEGIS_OEE.ACTION.ALERT
UNION ALL SELECT 'WORK_ORDER', COUNT(*) FROM AEGIS_OEE.ACTION.WORK_ORDER
UNION ALL SELECT 'WO_OUTBOX', COUNT(*) FROM AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX
UNION ALL SELECT 'PURCHASE_REQ', COUNT(*) FROM AEGIS_OEE.ACTION.PURCHASE_REQUISITION
UNION ALL SELECT 'WO_SCHEDULE', COUNT(*) FROM AEGIS_OEE.ACTION.WO_SCHEDULE;

SELECT 'DEMO RESET COMPLETE' AS STATUS;
