#!/usr/bin/env python3
"""AegisOEE Outbox Dispatcher — polls WORK_ORDER_OUTBOX for PENDING items,
dispatches via GitHub API / Slack webhook, and closes GitHub issues for
CLOSED/REJECTED work orders."""

import json, os, subprocess, sys, re

CONN = "aegis"
GITHUB_REPO = "SreekarReddyMarpadaga/AegisOEE"

def snow_sql(sql):
    subprocess.run(["snow", "sql", "--connection", CONN, "-q", sql],
                   capture_output=True, text=True)

def query_json(sql):
    r = subprocess.run(["snow", "sql", "--connection", CONN, "--format", "json", "-q", sql],
                       capture_output=True, text=True)
    if r.returncode != 0:
        return []
    try:
        return json.loads(r.stdout)
    except Exception:
        return []


def dispatch_pending(github_pat, slack_url):
    items = query_json("""
        SELECT OB.OUTBOX_ID, OB.WO_ID, OB.TARGET, OB.ATTEMPTS,
               WO.TITLE, WO.DESCRIPTION, WO.ASSET_ID, WO.PRIORITY, WO.APPROVED_BY,
               WO.ALERT_ID,
               AL.SEVERITY, AL.PREDICTED_MODE, AL.FAILURE_PROBABILITY,
               AL.CONFIDENCE, AL.OEE_IMPACT_EST
        FROM AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX OB
        JOIN AEGIS_OEE.ACTION.WORK_ORDER WO ON OB.WO_ID = WO.WO_ID
        LEFT JOIN AEGIS_OEE.ACTION.ALERT AL ON WO.ALERT_ID = AL.ALERT_ID
        WHERE OB.STATUS = 'PENDING'
        ORDER BY OB.TARGET
    """)
    if not items:
        return

    import requests
    print(f"[DISPATCHER] {len(items)} pending item(s)")

    for item in items:
        outbox_id = item["OUTBOX_ID"]
        wo_id = item["WO_ID"]
        target = item["TARGET"]
        title = item.get("TITLE") or "Work Order"
        desc = item.get("DESCRIPTION") or ""
        asset = item.get("ASSET_ID") or ""
        priority = item.get("PRIORITY") or "P3"
        approver = item.get("APPROVED_BY") or ""
        severity = item.get("SEVERITY") or priority
        mode = item.get("PREDICTED_MODE") or ""
        fp = item.get("FAILURE_PROBABILITY") or 0
        conf = item.get("CONFIDENCE") or 0
        oee_impact = item.get("OEE_IMPACT_EST") or 0
        alert_id = item.get("ALERT_ID") or ""

        try:
            if target == "GITHUB" and github_pat:
                # Fetch parts data for the issue body
                parts_rows = query_json(f"""
                    SELECT FMP.PART_ID, PI.PART_NAME, FMP.QTY_REQUIRED,
                           PI.ON_HAND_QTY - PI.RESERVED_QTY AS AVAILABLE,
                           GREATEST(0, FMP.QTY_REQUIRED - (PI.ON_HAND_QTY - PI.RESERVED_QTY)) AS SHORTAGE,
                           PI.UNIT_COST, PI.LEAD_TIME_DAYS
                    FROM AEGIS_OEE.CORE.FAILURE_MODE_PARTS FMP
                    JOIN AEGIS_OEE.CORE.PARTS_INVENTORY PI ON FMP.PART_ID = PI.PART_ID
                    WHERE FMP.FAILURE_MODE = '{mode}'
                      AND FMP.ASSET_TYPE = (SELECT ASSET_TYPE FROM AEGIS_OEE.CORE.ASSET WHERE ASSET_ID = '{asset}')
                """)
                reqs = query_json(f"""
                    SELECT REQ_ID, PART_ID, QTY, EST_TOTAL, SUPPLIER_NAME, LEAD_TIME_DAYS, STATUS
                    FROM AEGIS_OEE.ACTION.PURCHASE_REQUISITION WHERE WO_ID = '{wo_id}'
                """)

                parts_table = "| Part | Name | Req | Avail | Short | Cost | Lead |\n|---|---|---|---|---|---|---|\n"
                for p in parts_rows:
                    shortage_flag = " :warning:" if p.get("SHORTAGE", 0) > 0 else ""
                    parts_table += f"| {p['PART_ID']} | {p['PART_NAME']} | {p['QTY_REQUIRED']} | {p['AVAILABLE']} | {p['SHORTAGE']}{shortage_flag} | ${p['UNIT_COST']} | {p['LEAD_TIME_DAYS']}d |\n"

                reqs_section = ""
                if reqs:
                    reqs_section = "\n### Purchase Requisitions\n\n"
                    for r in reqs:
                        reqs_section += f"- **{r['REQ_ID']}**: {r['PART_ID']} x{r['QTY']} — ${r['EST_TOTAL']} — {r['SUPPLIER_NAME']} ({r['LEAD_TIME_DAYS']}d) — {r['STATUS']}\n"

                body_md = f"""## Work Order: `{wo_id}`

**Asset:** `{asset}` | **Priority:** {priority} | **Approved by:** {approver}

> {desc}

---

### Alert Details

| Field | Value |
|---|---|
| Severity | **{severity}** |
| Predicted Mode | `{mode}` |
| Confidence | {conf} |
| Failure Probability | {fp} |
| OEE Impact | {oee_impact} |
| Alert ID | `{alert_id}` |

---

### Parts Required

{parts_table}
{reqs_section}
---

### :rotating_light: Safety
> This work order requires on-site human verification before execution.

---
*Generated by AegisOEE Governed Action Loop*
"""
                labels = [s for s in [severity, mode, "maintenance"] if s]
                resp = requests.post(
                    f"https://api.github.com/repos/{GITHUB_REPO}/issues",
                    headers={"Authorization": f"token {github_pat}", "Accept": "application/vnd.github.v3+json"},
                    json={"title": title, "body": body_md, "labels": labels},
                    timeout=30,
                )
                if resp.status_code in (200, 201):
                    issue_url = resp.json().get("html_url", "")
                    safe_url = issue_url.replace("'", "''")
                    snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET STATUS='SENT', ATTEMPTS=ATTEMPTS+1 WHERE OUTBOX_ID='{outbox_id}'")
                    if issue_url:
                        snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER SET GITHUB_ISSUE_URL='{safe_url}' WHERE WO_ID='{wo_id}' AND GITHUB_ISSUE_URL IS NULL")
                    audit_detail = json.dumps({"issue_url": issue_url}).replace("'", "''")
                    snow_sql(f"INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT(AUDIT_ID,TS,ACTOR,ACTION,OBJECT_REF,DETAIL) SELECT 'AUD_GH_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),CURRENT_TIMESTAMP,'OUTBOX_DISPATCHER','GITHUB_SENT','{wo_id}',PARSE_JSON('{audit_detail}')")
                    print(f"  GITHUB SENT: {wo_id} -> {issue_url}")
                else:
                    err = resp.text[:200].replace("'", "''")
                    snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
                    print(f"  GITHUB FAILED ({resp.status_code}): {wo_id}")

            elif target == "SLACK" and slack_url:
                github_url_rows = query_json(f"SELECT GITHUB_ISSUE_URL FROM AEGIS_OEE.ACTION.WORK_ORDER WHERE WO_ID = '{wo_id}'")
                gh_url = github_url_rows[0].get("GITHUB_ISSUE_URL", "") if github_url_rows else ""
                gh_link = f"\n<{gh_url}|View GitHub Issue>" if gh_url else ""

                msg = {
                    "text": f"{severity} Work Order Approved: {title}",
                    "blocks": [
                        {"type": "header", "text": {"type": "plain_text", "text": ":rotating_light: AegisOEE Work Order Approved", "emoji": True}},
                        {"type": "section", "fields": [
                            {"type": "mrkdwn", "text": f"*Work Order:*\n`{wo_id}`"},
                            {"type": "mrkdwn", "text": f"*Asset:*\n`{asset}`"},
                            {"type": "mrkdwn", "text": f"*Failure Mode:*\n`{mode}`"},
                            {"type": "mrkdwn", "text": f"*Approved by:*\n{approver}"},
                        ]},
                        {"type": "section", "text": {"type": "mrkdwn", "text": f"*{title}*\n{desc}{gh_link}"}},
                        {"type": "context", "elements": [{"type": "mrkdwn", "text": "Generated by AegisOEE Governed Action Loop"}]},
                    ]
                }
                resp = requests.post(slack_url, json=msg, timeout=30)
                if resp.status_code == 200:
                    snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET STATUS='SENT', ATTEMPTS=ATTEMPTS+1 WHERE OUTBOX_ID='{outbox_id}'")
                    snow_sql(f"INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT(AUDIT_ID,TS,ACTOR,ACTION,OBJECT_REF,DETAIL) SELECT 'AUD_SL_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),CURRENT_TIMESTAMP,'OUTBOX_DISPATCHER','SLACK_SENT','{wo_id}',PARSE_JSON('{{\"status\":\"sent\"}}')")
                    print(f"  SLACK SENT: {wo_id}")
                else:
                    err = resp.text[:200].replace("'", "''")
                    snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
                    print(f"  SLACK FAILED ({resp.status_code}): {wo_id}")
            else:
                print(f"  SKIP: {target} for {wo_id} (no credential)")
        except Exception as e:
            err = str(e)[:200].replace("'", "''")
            snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
            print(f"  ERROR: {target} {wo_id} -> {e}")


def close_github_issues(github_pat):
    """Close GitHub issues for work orders that are CLOSED or REJECTED."""
    if not github_pat:
        return

    wo_to_close = query_json("""
        SELECT WO.WO_ID, WO.STATE, WO.GITHUB_ISSUE_URL
        FROM AEGIS_OEE.ACTION.WORK_ORDER WO
        WHERE WO.STATE IN ('CLOSED', 'REJECTED')
          AND WO.GITHUB_ISSUE_URL IS NOT NULL
          AND WO.GITHUB_ISSUE_URL != ''
          AND NOT EXISTS (
            SELECT 1 FROM AEGIS_OEE.ACTION.ACTION_AUDIT AA
            WHERE AA.ACTION = 'GITHUB_ISSUE_CLOSED'
              AND AA.OBJECT_REF = WO.WO_ID
          )
    """)
    if not wo_to_close:
        return

    import requests
    print(f"[DISPATCHER] {len(wo_to_close)} GitHub issue(s) to close")

    for wo in wo_to_close:
        wo_id = wo["WO_ID"]
        state = wo["STATE"]
        issue_url = wo["GITHUB_ISSUE_URL"]
        # Extract issue number from URL like .../issues/1
        match = re.search(r'/issues/(\d+)$', issue_url)
        if not match:
            print(f"  SKIP CLOSE: {wo_id} — can't parse issue number from {issue_url}")
            continue
        issue_number = match.group(1)

        try:
            # Close the issue
            api_url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{issue_number}"
            close_comment = f"Work order `{wo_id}` has been **{state}**. Closing this issue."
            if state == "REJECTED":
                close_comment += "\n\n> This work order was rejected and no maintenance action was taken."

            # Add closing comment
            requests.post(
                f"{api_url}/comments",
                headers={"Authorization": f"token {github_pat}", "Accept": "application/vnd.github.v3+json"},
                json={"body": close_comment},
                timeout=30,
            )
            # Close the issue
            resp = requests.patch(
                api_url,
                headers={"Authorization": f"token {github_pat}", "Accept": "application/vnd.github.v3+json"},
                json={"state": "closed", "state_reason": "completed" if state == "CLOSED" else "not_planned"},
                timeout=30,
            )
            if resp.status_code == 200:
                audit_detail = json.dumps({"issue_url": issue_url, "issue_number": issue_number, "wo_state": state}).replace("'", "''")
                snow_sql(f"INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT(AUDIT_ID,TS,ACTOR,ACTION,OBJECT_REF,DETAIL) SELECT 'AUD_GH_CLOSE_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),CURRENT_TIMESTAMP,'OUTBOX_DISPATCHER','GITHUB_ISSUE_CLOSED','{wo_id}',PARSE_JSON('{audit_detail}')")
                # Also send Slack notification about closure
                if slack_url := os.environ.get("SLACK_WEBHOOK_URL", ""):
                    requests.post(slack_url, json={
                        "text": f"GitHub Issue #{issue_number} closed — WO {wo_id} {state}",
                        "blocks": [
                            {"type": "section", "text": {"type": "mrkdwn", "text": f":white_check_mark: *Work Order {state}*\n`{wo_id}` — <{issue_url}|GitHub Issue #{issue_number}> closed."}},
                            {"type": "context", "elements": [{"type": "mrkdwn", "text": "AegisOEE Governed Action Loop"}]},
                        ]
                    }, timeout=30)
                print(f"  GITHUB CLOSED: {wo_id} issue #{issue_number} ({state})")
            else:
                print(f"  GITHUB CLOSE FAILED ({resp.status_code}): {wo_id}")
        except Exception as e:
            print(f"  ERROR closing issue: {wo_id} -> {e}")


def sync_github_status(github_pat):
    """Inbound sync: poll linked GitHub issues for WOs not yet in terminal state.
    On state transition → update WO, audit, release parts if cancelled, queue Slack."""
    if not github_pat:
        return
    wo_rows = query_json("""
        SELECT WO_ID, STATE, GITHUB_ISSUE_URL
        FROM AEGIS_OEE.ACTION.WORK_ORDER
        WHERE GITHUB_ISSUE_URL IS NOT NULL
          AND GITHUB_ISSUE_URL != ''
          AND STATE NOT IN ('RESOLVED','CANCELLED','CLOSED','REJECTED')
    """)
    if not wo_rows:
        return

    import requests
    print(f"[SYNC] Checking {len(wo_rows)} linked GitHub issue(s) for inbound state changes")

    for wo in wo_rows:
        wo_id = wo["WO_ID"]
        current_state = wo["STATE"]
        issue_url = wo["GITHUB_ISSUE_URL"]
        match = re.search(r'/issues/(\d+)$', issue_url)
        if not match:
            continue
        issue_number = match.group(1)

        try:
            api_url = f"https://api.github.com/repos/{GITHUB_REPO}/issues/{issue_number}"
            resp = requests.get(api_url, headers={
                "Authorization": f"token {github_pat}",
                "Accept": "application/vnd.github.v3+json",
            }, timeout=30)
            if resp.status_code != 200:
                print(f"  SKIP {wo_id}: GitHub API {resp.status_code}")
                continue

            issue = resp.json()
            gh_state = issue.get("state", "open")
            gh_reason = issue.get("state_reason", "")
            gh_closed_at = issue.get("closed_at", "")

            if gh_state != "closed":
                continue

            # Map GitHub close reason to WO state
            if gh_reason == "not_planned":
                new_state = "CANCELLED"
                audit_action = "WO_CANCELLED"
            else:
                new_state = "RESOLVED"
                audit_action = "WO_RESOLVED"

            # Idempotency: skip if already in this state
            if current_state == new_state:
                continue

            print(f"  TRANSITION: {wo_id} {current_state} -> {new_state} (GitHub #{issue_number} {gh_reason or 'completed'})")

            # 2a. Update WO state + close_reason + closed_at
            closed_at_sql = f"'{gh_closed_at}'" if gh_closed_at else "CURRENT_TIMESTAMP"
            reason_escaped = (gh_reason or 'completed').replace("'", "''")
            snow_sql(f"""
                UPDATE AEGIS_OEE.ACTION.WORK_ORDER
                SET STATE = '{new_state}',
                    CLOSE_REASON = '{reason_escaped}',
                    CLOSED_AT = TRY_TO_TIMESTAMP_TZ({closed_at_sql})
                WHERE WO_ID = '{wo_id}'
            """)

            # 2b. Audit row
            audit_detail = json.dumps({
                "source": "github_sync",
                "issue_url": issue_url,
                "issue_number": issue_number,
                "gh_state_reason": gh_reason,
                "previous_state": current_state,
            }).replace("'", "''")
            snow_sql(f"""
                INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT
                    (AUDIT_ID, TS, ACTOR, ACTION, OBJECT_REF, DETAIL)
                SELECT
                    'AUD_GHSYNC_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),
                    CURRENT_TIMESTAMP,
                    'GITHUB_SYNC',
                    '{audit_action}',
                    '{wo_id}',
                    PARSE_JSON('{audit_detail}')
            """)

            # 2c. On CANCELLED: release reserved parts
            if new_state == "CANCELLED":
                snow_sql(f"""
                    UPDATE AEGIS_OEE.CORE.PARTS_INVENTORY PI
                    SET PI.QTY_RESERVED = PI.QTY_RESERVED - PR.QTY_REQUESTED
                    FROM AEGIS_OEE.ACTION.PURCHASE_REQUISITION PR
                    WHERE PR.WO_ID = '{wo_id}'
                      AND PR.PART_ID = PI.PART_ID
                      AND PI.QTY_RESERVED >= PR.QTY_REQUESTED
                """)
                print(f"    Released reserved parts for {wo_id}")

            # 2d. Queue Slack notification
            slack_text = f"GitHub Issue #{issue_number} was closed ({gh_reason or 'completed'}) — WO `{wo_id}` → **{new_state}**"
            slack_escaped = slack_text.replace("'", "''")
            snow_sql(f"""
                INSERT INTO AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX
                    (OUTBOX_ID, WO_ID, TARGET, PAYLOAD, STATUS)
                SELECT
                    'OB_GHSYNC_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),
                    '{wo_id}',
                    'SLACK',
                    OBJECT_CONSTRUCT('text', '{slack_escaped}', 'blocks', ARRAY_CONSTRUCT(
                        OBJECT_CONSTRUCT('type','section','text',OBJECT_CONSTRUCT('type','mrkdwn','text',
                            ':arrows_counterclockwise: *{new_state}* via GitHub close\\n`{wo_id}` — <{issue_url}|Issue #{issue_number}> ({gh_reason or "completed"})'
                        )),
                        OBJECT_CONSTRUCT('type','context','elements',ARRAY_CONSTRUCT(
                            OBJECT_CONSTRUCT('type','mrkdwn','text','AegisOEE Governed Action Loop — Inbound Sync')
                        ))
                    )),
                    'PENDING'
            """)
            print(f"    Queued Slack notification for {wo_id}")

        except Exception as e:
            print(f"  ERROR syncing {wo_id}: {e}")


def main():
    github_pat = os.environ.get("GITHUB_PAT", "")
    slack_url = os.environ.get("SLACK_WEBHOOK_URL", "")

    dispatch_pending(github_pat, slack_url)
    close_github_issues(github_pat)
    sync_github_status(github_pat)
    # Dispatch any Slack items queued by the sync above
    dispatch_pending("", slack_url)

if __name__ == "__main__":
    main()
