#!/usr/bin/env bash
# AegisOEE Outbox Dispatcher — polls WORK_ORDER_OUTBOX for PENDING items
# and dispatches them via GitHub API / Slack webhook using cortex secrets.
# Designed to run as a cron job in the CoCo CLI session.

set -euo pipefail

CONN="aegis"

# Fetch PENDING outbox items
PENDING=$(snow sql --connection "$CONN" --format json -q "
  SELECT OB.OUTBOX_ID, OB.WO_ID, OB.TARGET, OB.PAYLOAD, OB.ATTEMPTS,
         WO.TITLE, WO.DESCRIPTION, WO.ASSET_ID, WO.PRIORITY, WO.APPROVED_BY,
         AL.SEVERITY, AL.PREDICTED_MODE, AL.FAILURE_PROBABILITY, AL.CONFIDENCE
  FROM AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX OB
  JOIN AEGIS_OEE.ACTION.WORK_ORDER WO ON OB.WO_ID = WO.WO_ID
  LEFT JOIN AEGIS_OEE.ACTION.ALERT AL ON WO.ALERT_ID = AL.ALERT_ID
  WHERE OB.STATUS = 'PENDING'
  ORDER BY OB.TARGET
" 2>/dev/null) || { echo "No pending items or query failed"; exit 0; }

COUNT=$(echo "$PENDING" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
if [ "$COUNT" = "0" ]; then
  exit 0
fi

echo "[$(date)] Dispatching $COUNT pending outbox items..."

echo "$PENDING" | python3 - "$CONN" <<'PYEOF'
import json, sys, os, subprocess

conn = sys.argv[1]
items = json.load(sys.stdin)

def snow_sql(sql):
    subprocess.run(["snow", "sql", "--connection", conn, "-q", sql],
                   capture_output=True, text=True)

def get_secret(key):
    r = subprocess.run(["bash", "-c", f'echo "${key}"'],
                       capture_output=True, text=True,
                       env={**os.environ})
    return r.stdout.strip()

github_pat = get_secret("GITHUB_PAT")
slack_url = get_secret("SLACK_WEBHOOK_URL")

for item in items:
    outbox_id = item["OUTBOX_ID"]
    wo_id = item["WO_ID"]
    target = item["TARGET"]
    title = item.get("TITLE", "Work Order")
    desc = item.get("DESCRIPTION", "")
    asset = item.get("ASSET_ID", "")
    priority = item.get("PRIORITY", "P3")
    approver = item.get("APPROVED_BY", "")
    severity = item.get("SEVERITY", priority)
    mode = item.get("PREDICTED_MODE", "")
    fp = item.get("FAILURE_PROBABILITY", 0)
    conf = item.get("CONFIDENCE", 0)

    try:
        if target == "GITHUB" and github_pat:
            import requests
            body = f"""## {title}

**Asset:** {asset} | **Priority:** {priority} | **Approved by:** {approver}

### Details
{desc}

### Alert Info
- **Failure mode:** {mode}
- **Failure probability:** {fp}
- **Confidence:** {conf}
- **Severity:** {severity}

### Safety
This work order requires on-site human verification before execution.

---
*Generated by AegisOEE Governed Action Loop*
"""
            resp = requests.post(
                "https://api.github.com/repos/SreekarReddyMarpadaga/AegisOEE/issues",
                headers={"Authorization": f"token {github_pat}", "Accept": "application/vnd.github.v3+json"},
                json={"title": title, "body": body, "labels": [severity, mode, "maintenance"]}
            )
            if resp.status_code in (200, 201):
                issue_url = resp.json().get("html_url", "")
                snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET STATUS='SENT', ATTEMPTS=ATTEMPTS+1 WHERE OUTBOX_ID='{outbox_id}'")
                if issue_url:
                    snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER SET GITHUB_ISSUE_URL='{issue_url}' WHERE WO_ID='{wo_id}' AND GITHUB_ISSUE_URL IS NULL")
                snow_sql(f"INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT(AUDIT_ID,TS,ACTOR,ACTION,OBJECT_REF,DETAIL) SELECT 'AUD_GH_SENT_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),CURRENT_TIMESTAMP,'OUTBOX_DISPATCHER','GITHUB_SENT','{wo_id}',PARSE_JSON('{json.dumps({\"issue_url\": issue_url})}')")
                print(f"  GITHUB SENT: {wo_id} -> {issue_url}")
            else:
                err = resp.text[:200].replace("'", "")
                snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
                print(f"  GITHUB FAILED: {wo_id} -> {resp.status_code}")

        elif target == "SLACK" and slack_url:
            import requests
            msg = {
                "text": f"{severity} Work Order Approved: {title}",
                "blocks": [
                    {"type": "header", "text": {"type": "plain_text", "text": f"{severity} Work Order Approved"}},
                    {"type": "section", "fields": [
                        {"type": "mrkdwn", "text": f"*Asset:* {asset}"},
                        {"type": "mrkdwn", "text": f"*Priority:* {priority}"},
                        {"type": "mrkdwn", "text": f"*Mode:* {mode}"},
                        {"type": "mrkdwn", "text": f"*Approver:* {approver}"},
                    ]},
                    {"type": "section", "text": {"type": "mrkdwn", "text": f"*Description:* {desc}"}},
                ]
            }
            resp = requests.post(slack_url, json=msg)
            if resp.status_code == 200:
                snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET STATUS='SENT', ATTEMPTS=ATTEMPTS+1 WHERE OUTBOX_ID='{outbox_id}'")
                snow_sql(f"INSERT INTO AEGIS_OEE.ACTION.ACTION_AUDIT(AUDIT_ID,TS,ACTOR,ACTION,OBJECT_REF,DETAIL) SELECT 'AUD_SL_SENT_'||TO_VARCHAR(CURRENT_TIMESTAMP,'YYYYMMDD_HH24MISSFF3'),CURRENT_TIMESTAMP,'OUTBOX_DISPATCHER','SLACK_SENT','{wo_id}',PARSE_JSON('{{\"status\":\"sent\"}}')")
                print(f"  SLACK SENT: {wo_id}")
            else:
                err = resp.text[:200].replace("'", "")
                snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
                print(f"  SLACK FAILED: {wo_id} -> {resp.status_code}")
        else:
            print(f"  SKIP: {target} for {wo_id} (no credentials)")
    except Exception as e:
        err = str(e)[:200].replace("'", "")
        snow_sql(f"UPDATE AEGIS_OEE.ACTION.WORK_ORDER_OUTBOX SET ATTEMPTS=ATTEMPTS+1, LAST_ERROR='{err}' WHERE OUTBOX_ID='{outbox_id}'")
        print(f"  ERROR: {target} {wo_id} -> {e}")

PYEOF
