-- =============================================================================
-- 02_tables.sql — All tables in CORE, RAW, ACTION, ML, TEST, SEMANTIC schemas
-- Exported from live AEGIS_OEE via GET_DDL, includes FINAL state
-- (WORK_ORDER has CLOSE_REASON/CLOSED_AT columns).
-- =============================================================================

USE DATABASE AEGIS_OEE;
USE WAREHOUSE AEGIS_WH;

-- ── CORE schema ──

CREATE OR REPLACE TABLE CORE.ASSET (
    ASSET_ID VARCHAR(16777216) NOT NULL,
    LINE_ID VARCHAR(16777216) NOT NULL,
    SITE_ID VARCHAR(16777216) NOT NULL,
    ASSET_TYPE VARCHAR(16777216) NOT NULL,
    MANUFACTURER VARCHAR(16777216),
    INSTALL_DATE DATE,
    CRITICALITY NUMBER(1,0) NOT NULL,
    IDEAL_RPM NUMBER(10,2),
    IDEAL_CYCLE_S NUMBER(10,2),
    TEMP_LIMIT_C NUMBER(10,2),
    VIB_ALERT_MM_S NUMBER(10,4),
    VIB_DANGER_MM_S NUMBER(10,4),
    CONSTRAINT PK_ASSET PRIMARY KEY (ASSET_ID)
);

CREATE OR REPLACE TABLE CORE.SHIFT_CALENDAR (
    SHIFT_DATE DATE NOT NULL,
    SHIFT_CODE VARCHAR(16777216) NOT NULL,
    START_TS TIMESTAMP_TZ(9) NOT NULL,
    END_TS TIMESTAMP_TZ(9) NOT NULL,
    PLANNED_MINUTES NUMBER(10,0) NOT NULL DEFAULT 480,
    PLANNED_DOWNTIME_MINUTES NUMBER(10,0) NOT NULL DEFAULT 0,
    CONSTRAINT PK_SHIFT_CALENDAR PRIMARY KEY (SHIFT_DATE, SHIFT_CODE)
);

CREATE OR REPLACE TABLE CORE.PRODUCTION_ORDER (
    ORDER_ID VARCHAR(16777216) NOT NULL,
    LINE_ID VARCHAR(16777216) NOT NULL,
    PRODUCT_CODE VARCHAR(16777216) NOT NULL,
    PLANNED_QTY NUMBER(10,0) NOT NULL,
    IDEAL_CYCLE_S NUMBER(10,2) NOT NULL,
    PLANNED_START_TS TIMESTAMP_TZ(9) NOT NULL,
    PLANNED_END_TS TIMESTAMP_TZ(9) NOT NULL,
    CONSTRAINT PK_PRODUCTION_ORDER PRIMARY KEY (ORDER_ID)
);

CREATE OR REPLACE TABLE CORE.DOWNTIME_EVENT (
    EVENT_ID VARCHAR(16777216) NOT NULL,
    ASSET_ID VARCHAR(16777216) NOT NULL,
    START_TS TIMESTAMP_TZ(9) NOT NULL,
    END_TS TIMESTAMP_TZ(9) NOT NULL,
    IS_PLANNED BOOLEAN NOT NULL,
    REASON_CODE VARCHAR(16777216),
    FAILURE_MODE VARCHAR(16777216),
    MINUTES FLOAT NOT NULL,
    CONSTRAINT PK_DOWNTIME_EVENT PRIMARY KEY (EVENT_ID)
);

CREATE OR REPLACE TABLE CORE.MAINTENANCE_HISTORY (
    WO_HIST_ID VARCHAR(16777216) NOT NULL,
    ASSET_ID VARCHAR(16777216) NOT NULL,
    COMPLETED_TS TIMESTAMP_TZ(9) NOT NULL,
    FAILURE_CODE VARCHAR(16777216),
    FINDING VARCHAR(16777216),
    ACTION_TAKEN VARCHAR(16777216),
    PARTS_USED VARCHAR(16777216),
    LABOR_HOURS FLOAT,
    TECHNICIAN_NOTE VARCHAR(16777216),
    CONSTRAINT PK_MAINTENANCE_HISTORY PRIMARY KEY (WO_HIST_ID)
);

CREATE OR REPLACE TABLE CORE.PARTS_INVENTORY (
    PART_ID VARCHAR(16777216) NOT NULL,
    PART_NAME VARCHAR(16777216) NOT NULL,
    CATEGORY VARCHAR(16777216),
    ON_HAND_QTY NUMBER(10,0) NOT NULL DEFAULT 0,
    RESERVED_QTY NUMBER(10,0) NOT NULL DEFAULT 0,
    REORDER_POINT NUMBER(10,0) NOT NULL DEFAULT 0,
    UNIT_COST FLOAT NOT NULL,
    SUPPLIER_NAME VARCHAR(16777216),
    LEAD_TIME_DAYS NUMBER(5,0) NOT NULL DEFAULT 7,
    BIN_LOCATION VARCHAR(16777216),
    CONSTRAINT PK_PARTS_INVENTORY PRIMARY KEY (PART_ID)
);

CREATE OR REPLACE TABLE CORE.FAILURE_MODE_PARTS (
    FAILURE_MODE VARCHAR(16777216) NOT NULL,
    ASSET_TYPE VARCHAR(16777216) NOT NULL,
    PART_ID VARCHAR(16777216) NOT NULL,
    QTY_REQUIRED NUMBER(10,0) NOT NULL DEFAULT 1
);

-- ── RAW schema ──

CREATE OR REPLACE TABLE RAW.SENSOR_TELEMETRY (
    ASSET_ID VARCHAR(16777216) NOT NULL,
    TS TIMESTAMP_TZ(9) NOT NULL,
    VIBRATION_RMS FLOAT,
    VIBRATION_KURTOSIS FLOAT,
    TEMP_C FLOAT,
    RPM FLOAT,
    LOAD_PCT FLOAT,
    QUALITY_FLAG VARCHAR(16777216) DEFAULT 'OK',
    INGEST_TS TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTION_EVENT (
    ASSET_ID VARCHAR(16777216) NOT NULL,
    TS TIMESTAMP_TZ(9) NOT NULL,
    ORDER_ID VARCHAR(16777216),
    STATE VARCHAR(16777216) NOT NULL,
    PRODUCED_COUNT NUMBER(10,0) DEFAULT 0,
    GOOD_COUNT NUMBER(10,0) DEFAULT 0,
    REJECT_COUNT NUMBER(10,0) DEFAULT 0,
    CYCLE_TIME_S FLOAT
);

-- ── ACTION schema ──

CREATE OR REPLACE TABLE ACTION.ALERT (
    ALERT_ID VARCHAR(16777216) NOT NULL,
    ASSET_ID VARCHAR(16777216) NOT NULL,
    ONSET_TS TIMESTAMP_TZ(9) NOT NULL,
    SEVERITY VARCHAR(16777216) NOT NULL,
    CONFIDENCE FLOAT,
    FAILURE_PROBABILITY FLOAT,
    PREDICTED_MODE VARCHAR(16777216),
    OEE_IMPACT_EST FLOAT,
    STATUS VARCHAR(16777216) NOT NULL DEFAULT 'NEW',
    EVIDENCE VARIANT,
    CONSTRAINT PK_ALERT PRIMARY KEY (ALERT_ID)
);

CREATE OR REPLACE TABLE ACTION.WORK_ORDER (
    WO_ID VARCHAR(16777216) NOT NULL,
    ALERT_ID VARCHAR(16777216),
    ASSET_ID VARCHAR(16777216) NOT NULL,
    PRIORITY VARCHAR(16777216),
    STATE VARCHAR(16777216) NOT NULL DEFAULT 'DRAFT',
    TITLE VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    EVIDENCE VARIANT,
    GITHUB_ISSUE_URL VARCHAR(16777216),
    APPROVED_BY VARCHAR(16777216),
    APPROVED_TS TIMESTAMP_TZ(9),
    CLOSE_REASON VARCHAR(16777216),
    CLOSED_AT TIMESTAMP_TZ(9),
    CONSTRAINT PK_WORK_ORDER PRIMARY KEY (WO_ID)
);

CREATE OR REPLACE TABLE ACTION.WORK_ORDER_OUTBOX (
    OUTBOX_ID VARCHAR(16777216) NOT NULL,
    WO_ID VARCHAR(16777216) NOT NULL,
    TARGET VARCHAR(16777216) NOT NULL,
    PAYLOAD VARIANT,
    ATTEMPTS NUMBER(5,0) DEFAULT 0,
    LAST_ERROR VARCHAR(16777216),
    STATUS VARCHAR(16777216) NOT NULL DEFAULT 'PENDING'
);

CREATE OR REPLACE TABLE ACTION.ACTION_AUDIT (
    AUDIT_ID VARCHAR(16777216) NOT NULL,
    TS TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ACTOR VARCHAR(16777216) NOT NULL,
    ACTION VARCHAR(16777216) NOT NULL,
    OBJECT_REF VARCHAR(16777216),
    DETAIL VARIANT
);

CREATE OR REPLACE TABLE ACTION.PURCHASE_REQUISITION (
    REQ_ID VARCHAR(16777216) NOT NULL,
    WO_ID VARCHAR(16777216),
    PART_ID VARCHAR(16777216) NOT NULL,
    QTY NUMBER(10,0) NOT NULL,
    EST_UNIT_COST FLOAT,
    EST_TOTAL FLOAT,
    SUPPLIER_NAME VARCHAR(16777216),
    LEAD_TIME_DAYS NUMBER(5,0),
    RFQ_TEXT VARCHAR(16777216),
    STATUS VARCHAR(16777216) NOT NULL DEFAULT 'PENDING_QUOTE',
    CREATED_TS TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_PURCHASE_REQUISITION PRIMARY KEY (REQ_ID)
);

-- ── ML schema ──

CREATE OR REPLACE TABLE ML.ANOMALY_EVENTS (
    ASSET_ID VARCHAR(16777216) NOT NULL,
    TS TIMESTAMP_TZ(9) NOT NULL,
    SERIES_NAME VARCHAR(16777216) NOT NULL,
    IS_ANOMALY BOOLEAN,
    DISTANCE FLOAT,
    PERCENTILE FLOAT,
    FORECAST FLOAT,
    LOWER FLOAT,
    UPPER FLOAT
);

CREATE OR REPLACE TABLE ML.SIGNAL_FORECASTS (
    SERIES_TYPE VARCHAR(16777216) NOT NULL,
    SERIES_ID VARCHAR(16777216) NOT NULL,
    TS TIMESTAMP_NTZ(9) NOT NULL,
    FORECAST FLOAT,
    LOWER_BOUND FLOAT,
    UPPER_BOUND FLOAT,
    GENERATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ── SEMANTIC schema ──

CREATE OR REPLACE TABLE SEMANTIC.MAINTENANCE_DOCS (
    DOC_ID VARCHAR(16777216) NOT NULL,
    ASSET_ID VARCHAR(16777216),
    DOC_TYPE VARCHAR(16777216),
    TITLE VARCHAR(16777216),
    CONTENT VARCHAR(16777216),
    SOURCE VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ── TEST schema ──

CREATE OR REPLACE TABLE TEST.GROUND_TRUTH_FAILURES (
    FAILURE_ID VARCHAR(16777216) NOT NULL,
    ASSET_ID VARCHAR(16777216) NOT NULL,
    FAILURE_MODE VARCHAR(16777216) NOT NULL,
    DEGRADATION_START_TS TIMESTAMP_TZ(9) NOT NULL,
    FAILURE_TS TIMESTAMP_TZ(9) NOT NULL,
    SEVERITY VARCHAR(16777216),
    CONSTRAINT PK_GROUND_TRUTH_FAILURES PRIMARY KEY (FAILURE_ID)
);

CREATE OR REPLACE TABLE TEST.VALIDATION_RESULTS (
    CHECK_NAME VARCHAR(16777216) NOT NULL,
    STATUS VARCHAR(16777216) NOT NULL,
    DETAIL VARCHAR(16777216),
    CHECKED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TEST.ML_METRICS (
    METRIC_NAME VARCHAR(16777216),
    METRIC_VALUE FLOAT,
    DETAIL VARCHAR(16777216),
    EVALUATED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TEST.AGENT_EVAL_RESULTS (
    EVAL_ID VARCHAR(16777216) NOT NULL,
    EVAL_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CATEGORY VARCHAR(16777216),
    QUESTION VARCHAR(16777216),
    EXPECTED_GROUNDING VARCHAR(16777216),
    RESPONSE_SUMMARY VARCHAR(16777216),
    PASS BOOLEAN,
    FAILURE_REASON VARCHAR(16777216),
    LATENCY_S FLOAT
);

CREATE OR REPLACE TABLE TEST.ACTION_GUARDRAIL_RESULTS (
    TEST_NAME VARCHAR(16777216) NOT NULL,
    RESULT VARCHAR(16777216) NOT NULL,
    DETAIL VARCHAR(16777216),
    TESTED_AT TIMESTAMP_TZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TEST.ENV_PROBES (
    PROBE_NAME VARCHAR(16777216),
    RESULT VARCHAR(16777216),
    DETAIL VARCHAR(16777216),
    PROBED_AT TIMESTAMP_TZ(9)
);
