-- =============================================================================
-- 06_semantic_search.sql — Semantic View + Cortex Search Service + Doc Load
-- Exported from live AEGIS_OEE. Semantic view deployed from YAML via 
-- SYSTEM$CREATE_SEMANTIC_VIEW_FROM_YAML or cortex agent-studio.
-- =============================================================================

USE DATABASE AEGIS_OEE;
USE WAREHOUSE AEGIS_WH;

-- ── Semantic View ──
-- The semantic view is deployed from the YAML file semantic/manufacturing_operations.yaml.
-- Method 1 (CLI): cortex agent-studio sv-deploy --file-path MANUFACTURING_OPERATIONS.sv.yaml --fqn AEGIS_OEE.SEMANTIC.MANUFACTURING_OPERATIONS
-- Method 2 (SQL): Use the DDL below (exported from live via GET_DDL)

create or replace semantic view MANUFACTURING_OPERATIONS
	tables (
		AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE comment='Shift-level OEE fact table. Each row = one asset in one shift. To compute aggregate OEE correctly, always re-derive from sums: Availability = SUM(RUN_MIN) / SUM(PLANNED_MIN), Performance = LEAST(SUM(IDEAL_CYCLE_S * TOTAL_COUNT) / (SUM(RUN_MIN) * 60), 1.0), Quality = SUM(GOOD_COUNT) / SUM(TOTAL_COUNT), OEE = Availability * Performance * Quality. Never average the pre-computed AVAILABILITY, PERFORMANCE, QUALITY, or OEE columns across rows.
',
		AEGIS_OEE.CORE.ASSET primary key (ASSET_ID) comment='Asset master dimension. Contains static attributes for each machine/equipment. 10 assets across 2 lines at site HYD_PRECISION. Criticality 1-5 (5 = most critical).
',
		AEGIS_OEE.CORE.DOWNTIME_EVENT comment='Downtime events for each asset. Each row is one downtime episode with start/end timestamps. IS_PLANNED=TRUE for scheduled maintenance, FALSE for unplanned breakdowns. FAILURE_MODE indicates the root cause (BEARING_WEAR, LUBRICATION_LOSS, etc.).
',
		AEGIS_OEE.CORE.PRODUCTION_ORDER comment='Production orders assigned to lines. Each order has a product code, planned quantity, and a planned time window. Used for production scheduling context.
',
		AEGIS_OEE.ACTION.ALERT primary key (ALERT_ID) comment='Predictive maintenance alerts generated by the ML pipeline. Severity: P1 (critical), P2 (warning), P3 (informational). Status: NEW, TRIAGED, ACKED, SUPPRESSED, CLOSED.
',
		AEGIS_OEE.ACTION.WORK_ORDER comment='Maintenance work orders linked to alerts. State lifecycle: DRAFT -> APPROVED -> SYNCED -> CLOSED (or REJECTED). The agent proposes work orders but never approves them - human approval is required.
',
		AEGIS_OEE.FEATURES.DT_ASSET_HEALTH comment='Current health status for each asset. Updated continuously via Dynamic Table. Health score 0-100 (higher = healthier). Risk levels: LOW, MEDIUM, HIGH, CRITICAL.
',
		AEGIS_OEE.SEMANTIC.V_MTBF_MTTR comment='Asset-level reliability metrics: Mean Time Between Failures (MTBF) and Mean Time To Repair (MTTR). MTBF = total run time / failure count. MTTR = total unplanned downtime / failure count.
'
	)
	relationships (
		OEE_TO_ASSET as DT_SHIFT_OEE(ASSET_ID) references ASSET(ASSET_ID),
		DOWNTIME_TO_ASSET as DOWNTIME_EVENT(ASSET_ID) references ASSET(ASSET_ID),
		ALERT_TO_ASSET as ALERT(ASSET_ID) references ASSET(ASSET_ID),
		WO_TO_ALERT as WORK_ORDER(ALERT_ID) references ALERT(ALERT_ID),
		WO_TO_ASSET as WORK_ORDER(ASSET_ID) references ASSET(ASSET_ID),
		HEALTH_TO_ASSET as DT_ASSET_HEALTH(ASSET_ID) references ASSET(ASSET_ID),
		MTBF_TO_ASSET as V_MTBF_MTTR(ASSET_ID) references ASSET(ASSET_ID)
	)
	facts (
		DT_SHIFT_OEE.PLANNED_MIN as PLANNED_MIN with synonyms=('planned production time','planned minutes','available time') comment='Planned production time in minutes (shift minutes minus planned downtime). Denominator for Availability.',
		DT_SHIFT_OEE.DOWNTIME_MIN as DOWNTIME_MIN with synonyms=('downtime','unplanned downtime','stoppage minutes','outage') comment='Unplanned downtime minutes allocated to this asset-shift by time overlap with downtime events',
		DT_SHIFT_OEE.RUN_MIN as RUN_MIN with synonyms=('run time','operating time','uptime') comment='Actual running time in minutes (planned minus unplanned downtime). Numerator for Availability.',
		DT_SHIFT_OEE.TOTAL_COUNT as TOTAL_COUNT with synonyms=('total production','total units','produced count','output','throughput') comment='Total units produced in the shift (good + rejected)',
		DT_SHIFT_OEE.GOOD_COUNT as GOOD_COUNT with synonyms=('good units','good production','quality units','conforming units') comment='Good (non-defective) units produced in the shift',
		DT_SHIFT_OEE.REJECT_COUNT as REJECT_COUNT with synonyms=('rejects','defects','scrap','bad units','nonconforming') comment='Rejected or defective units produced in the shift',
		DT_SHIFT_OEE.IDEAL_CYCLE_S as IDEAL_CYCLE_S comment='Ideal cycle time in seconds per unit for this asset, used in Performance calculation',
		ASSET.IDEAL_RPM as IDEAL_RPM comment='Nominal/ideal RPM for the asset',
		ASSET.TEMP_LIMIT_C as TEMP_LIMIT_C comment='Maximum safe temperature in Celsius',
		ASSET.VIB_ALERT_MM_S as VIB_ALERT_MM_S comment='Vibration alert threshold in mm/s (ISO 10816)',
		ASSET.VIB_DANGER_MM_S as VIB_DANGER_MM_S comment='Vibration danger threshold in mm/s (ISO 10816)',
		DOWNTIME_EVENT.DOWNTIME_MINUTES as MINUTES with synonyms=('downtime duration','outage duration','stoppage time') comment='Duration of the downtime event in minutes',
		PRODUCTION_ORDER.PLANNED_QTY as PLANNED_QTY with synonyms=('planned quantity','target quantity') comment='Planned quantity of units to produce',
		ALERT.CONFIDENCE as CONFIDENCE comment='Model confidence score (0 to 1). Below 0.5 = observe only, no work order.',
		ALERT.FAILURE_PROBABILITY as FAILURE_PROBABILITY with synonyms=('failure risk','failure likelihood') comment='Probability of failure within 24 hours (0 to 1)',
		ALERT.OEE_IMPACT_EST as OEE_IMPACT_EST with synonyms=('estimated OEE loss','OEE impact') comment='Estimated OEE percentage loss if the predicted failure occurs',
		DT_ASSET_HEALTH.HEALTH_SCORE as HEALTH_SCORE with synonyms=('health','equipment health','condition score') comment='Overall health score from 0 (failing) to 100 (perfect)',
		DT_ASSET_HEALTH.ANOMALY_DISTANCE as ANOMALY_DISTANCE with synonyms=('anomaly score') comment='Anomaly distance from the ML model - higher values indicate more anomalous behavior',
		DT_ASSET_HEALTH.FAILURE_PROBABILITY_24H as FAILURE_PROBABILITY_24H with synonyms=('failure probability','failure risk','risk score') comment='ML-predicted probability of failure within the next 24 hours (0 to 1)',
		V_MTBF_MTTR.FAILURE_COUNT as FAILURE_COUNT with synonyms=('failures','breakdown count') comment='Number of unplanned failures recorded for this asset',
		V_MTBF_MTTR.TOTAL_UNPLANNED_DOWNTIME_MIN as TOTAL_UNPLANNED_DOWNTIME_MIN comment='Total unplanned downtime in minutes across all failures',
		V_MTBF_MTTR.TOTAL_RUN_MIN_MTBF as TOTAL_RUN_MIN comment='Total running time in minutes',
		V_MTBF_MTTR.MTBF_MIN as MTBF_MIN with synonyms=('MTBF','mean time between failures') comment='Mean Time Between Failures in minutes',
		V_MTBF_MTTR.MTTR_MIN as MTTR_MIN with synonyms=('MTTR','mean time to repair','repair time') comment='Mean Time To Repair in minutes'
	)
	dimensions (
		DT_SHIFT_OEE.LINE_ID as LINE_ID with synonyms=('line','production line') comment='Production line identifier (LINE_1 or LINE_2)',
		DT_SHIFT_OEE.ASSET_ID as ASSET_ID with synonyms=('asset','machine','equipment','device') comment='Unique asset/machine identifier (e.g. CNC_01_SPINDLE, COOLANT_PUMP_01)',
		DT_SHIFT_OEE.SHIFT_CODE as SHIFT_CODE with synonyms=('shift','shift name') comment='Shift identifier: A (morning 06:00-14:00 IST) or B (afternoon 14:00-22:00 IST)',
		DT_SHIFT_OEE.SHIFT_DATE as SHIFT_DATE with synonyms=('date','day','production date') comment='Calendar date of the shift',
		ASSET.ASSET_ID as ASSET_ID with synonyms=('asset','machine','equipment') comment='Unique asset identifier (primary key)',
		ASSET.LINE_ID as LINE_ID with synonyms=('line') comment='Production line the asset belongs to',
		ASSET.SITE_ID as SITE_ID with synonyms=('site','plant','factory') comment='Plant/site identifier (HYD_PRECISION)',
		ASSET.ASSET_TYPE as ASSET_TYPE with synonyms=('machine type','equipment type','asset category') comment='Type/category of the asset: CNC spindle, coolant pump, servo motor, conveyor gearbox, air compressor',
		ASSET.MANUFACTURER as MANUFACTURER comment='Equipment manufacturer name',
		ASSET.CRITICALITY as CRITICALITY with synonyms=('importance','priority rating') comment='Asset criticality rating from 1 (lowest) to 5 (highest). CNC_01_SPINDLE is criticality 5.',
		ASSET.INSTALL_DATE as INSTALL_DATE comment='Date the asset was installed',
		DOWNTIME_EVENT.EVENT_ID as EVENT_ID comment='Unique downtime event identifier',
		DOWNTIME_EVENT.DT_ASSET_ID as ASSET_ID with synonyms=('asset') comment='Asset that experienced the downtime',
		DOWNTIME_EVENT.IS_PLANNED as IS_PLANNED with synonyms=('planned downtime','scheduled') comment='Whether the downtime was planned (TRUE) or unplanned breakdown (FALSE)',
		DOWNTIME_EVENT.REASON_CODE as REASON_CODE with synonyms=('reason','cause code') comment='Reason code for the downtime event',
		DOWNTIME_EVENT.FAILURE_MODE as FAILURE_MODE with synonyms=('failure type','fault mode','breakdown cause') comment='Failure mode: BEARING_WEAR, LUBRICATION_LOSS, COOLING_RESTRICTION, RPM_INSTABILITY, SENSOR_FAULT',
		DOWNTIME_EVENT.START_TS as START_TS with synonyms=('downtime start') comment='Downtime start timestamp',
		DOWNTIME_EVENT.END_TS as END_TS with synonyms=('downtime end') comment='Downtime end timestamp',
		PRODUCTION_ORDER.ORDER_ID as ORDER_ID with synonyms=('order','production order','PO') comment='Unique production order identifier',
		PRODUCTION_ORDER.PO_LINE_ID as LINE_ID comment='Production line assigned to this order',
		PRODUCTION_ORDER.PRODUCT_CODE as PRODUCT_CODE with synonyms=('product','part number','SKU') comment='Product being manufactured (e.g. PART_A100, PART_C300)',
		PRODUCTION_ORDER.PLANNED_START_TS as PLANNED_START_TS comment='Planned start timestamp for the order',
		PRODUCTION_ORDER.PLANNED_END_TS as PLANNED_END_TS comment='Planned end timestamp for the order',
		ALERT.ALERT_ID as ALERT_ID comment='Unique alert identifier',
		ALERT.ALERT_ASSET_ID as ASSET_ID with synonyms=('asset') comment='Asset the alert is for',
		ALERT.SEVERITY as SEVERITY with synonyms=('alert severity','priority','alert level') comment='Alert severity: P1 (critical, score >= 0.5), P2 (warning, >= 0.25), P3 (informational)',
		ALERT.PREDICTED_MODE as PREDICTED_MODE with synonyms=('predicted failure','predicted fault') comment='Predicted failure mode (BEARING_WEAR, LUBRICATION_LOSS, COOLING_RESTRICTION, RPM_INSTABILITY, SENSOR_FAULT)',
		ALERT.ALERT_STATUS as STATUS with synonyms=('alert state','status') comment='Current alert status: NEW, TRIAGED, ACKED, SUPPRESSED, CLOSED',
		ALERT.ONSET_TS as ONSET_TS with synonyms=('alert time','alert date') comment='Timestamp when the alert was first raised',
		WORK_ORDER.WO_ID as WO_ID with synonyms=('work order','WO','maintenance order') comment='Unique work order identifier',
		WORK_ORDER.WO_ALERT_ID as ALERT_ID comment='Alert that triggered this work order',
		WORK_ORDER.WO_ASSET_ID as ASSET_ID comment='Asset the work order is for',
		WORK_ORDER.WO_PRIORITY as PRIORITY with synonyms=('priority') comment='Work order priority (P1, P2, P3)',
		WORK_ORDER.WO_STATE as STATE with synonyms=('work order status','WO state') comment='Work order state: DRAFT, APPROVED, SYNCED, CLOSED, REJECTED',
		WORK_ORDER.WO_TITLE as TITLE comment='Work order title describing the maintenance action',
		WORK_ORDER.APPROVED_TS as APPROVED_TS comment='Timestamp when the work order was approved',
		DT_ASSET_HEALTH.HEALTH_ASSET_ID as ASSET_ID with synonyms=('asset') comment='Asset identifier',
		DT_ASSET_HEALTH.PREDICTED_FAILURE_MODE as PREDICTED_MODE with synonyms=('predicted mode','failure prediction') comment='ML-predicted most likely failure mode (if any)',
		DT_ASSET_HEALTH.RISK_LEVEL as RISK_LEVEL with synonyms=('risk','risk status','health status') comment='Current risk level: LOW, MEDIUM, HIGH, CRITICAL',
		DT_ASSET_HEALTH.LAST_READING_TS as LAST_READING_TS comment='Timestamp of the most recent sensor reading used for health scoring',
		V_MTBF_MTTR.MTBF_ASSET_ID as ASSET_ID with synonyms=('asset') comment='Asset identifier',
		V_MTBF_MTTR.MTBF_ASSET_TYPE as ASSET_TYPE with synonyms=('machine type') comment='Type of asset (CNC spindle, coolant pump, etc.)',
		V_MTBF_MTTR.MTBF_LINE_ID as LINE_ID comment='Production line'
	)
	metrics (
		DT_SHIFT_OEE.TOTAL_PLANNED_MIN as SUM(PLANNED_MIN) with synonyms=('total planned time') comment='Total planned production minutes across shifts',
		DT_SHIFT_OEE.TOTAL_DOWNTIME_MIN as SUM(DOWNTIME_MIN) with synonyms=('total downtime','total stoppage') comment='Total unplanned downtime minutes across shifts',
		DT_SHIFT_OEE.TOTAL_RUN_MIN as SUM(RUN_MIN) with synonyms=('total uptime','total run time') comment='Total running time in minutes across shifts',
		DT_SHIFT_OEE.TOTAL_PRODUCED as SUM(TOTAL_COUNT) with synonyms=('total output','total production') comment='Total units produced across shifts',
		DT_SHIFT_OEE.TOTAL_GOOD as SUM(GOOD_COUNT) comment='Total good units produced across shifts',
		DT_SHIFT_OEE.TOTAL_REJECTS as SUM(REJECT_COUNT) with synonyms=('total scrap','total defects') comment='Total rejected units across shifts',
		DT_SHIFT_OEE.AVAILABILITY as SUM(RUN_MIN) / NULLIF(SUM(PLANNED_MIN), 0) with synonyms=('availability rate','uptime rate') comment='Availability rate = SUM(RUN_MIN) / SUM(PLANNED_MIN). Measures uptime fraction. A value of 1.0 means no unplanned downtime.
',
		DT_SHIFT_OEE.PERFORMANCE as LEAST(SUM(IDEAL_CYCLE_S * TOTAL_COUNT) / NULLIF(SUM(RUN_MIN) * 60, 0), 1.0) with synonyms=('performance rate','speed efficiency') comment='Performance rate = SUM(IDEAL_CYCLE_S * TOTAL_COUNT) / (SUM(RUN_MIN) * 60), capped at 1.0. Measures speed efficiency relative to ideal cycle time.
',
		DT_SHIFT_OEE.QUALITY as SUM(GOOD_COUNT) / NULLIF(SUM(TOTAL_COUNT), 0) with synonyms=('quality rate','yield','first pass yield') comment='Quality rate = SUM(GOOD_COUNT) / SUM(TOTAL_COUNT). Measures first-pass yield.
',
		DT_SHIFT_OEE.OEE as (SUM(RUN_MIN) / NULLIF(SUM(PLANNED_MIN), 0)) * LEAST(SUM(IDEAL_CYCLE_S * TOTAL_COUNT) / NULLIF(SUM(RUN_MIN) * 60, 0), 1.0) * (SUM(GOOD_COUNT) / NULLIF(SUM(TOTAL_COUNT), 0)) with synonyms=('overall equipment effectiveness','equipment efficiency','OEE score') comment='Overall Equipment Effectiveness = Availability x Performance x Quality. Always derived from sums, never averaged. Typical range 0.55-0.85.
',
		DOWNTIME_EVENT.TOTAL_DOWNTIME_EVENTS as COUNT(*) with synonyms=('number of events','event count') comment='Count of downtime events',
		DOWNTIME_EVENT.SUM_DOWNTIME_MINUTES as SUM(MINUTES) with synonyms=('total downtime duration') comment='Total downtime minutes from events',
		ALERT.ALERT_COUNT as COUNT(*) with synonyms=('number of alerts','alert volume') comment='Total count of alerts',
		ALERT.TOTAL_OEE_IMPACT as SUM(OEE_IMPACT_EST) with synonyms=('total OEE loss','cumulative OEE impact') comment='Sum of estimated OEE loss across alerts',
		WORK_ORDER.WO_COUNT as COUNT(*) with synonyms=('number of work orders','work order count') comment='Count of work orders'
	)
	comment='Semantic model for manufacturing operations at Hyderabad Precision Components (HYD_PRECISION). Covers OEE (Overall Equipment Effectiveness) analytics at shift grain, asset health monitoring, predictive maintenance alerts, work orders, downtime analysis, and reliability metrics (MTBF/MTTR). Plant has 2 lines (LINE_1, LINE_2) with 10 assets. Shifts: A (06:00-14:00 IST), B (14:00-22:00 IST). OEE = Availability x Performance x Quality. Always recompute OEE from sums, never average percentages.
'
	ai_sql_generation 'When computing OEE metrics across multiple rows, always re-derive from sums of numerators and denominators. Never average pre-computed ratios like AVAILABILITY, PERFORMANCE, QUALITY, or OEE columns. The correct formulas are: Availability = SUM(RUN_MIN) / SUM(PLANNED_MIN), Performance = LEAST(SUM(IDEAL_CYCLE_S * TOTAL_COUNT) / (SUM(RUN_MIN) * 60), 1.0), Quality = SUM(GOOD_COUNT) / SUM(TOTAL_COUNT), OEE = Availability * Performance * Quality. Use NULLIF to prevent division by zero. For MTBF and MTTR, these are pre-computed per asset in V_MTBF_MTTR. The plant is Hyderabad Precision Components with lines LINE_1 and LINE_2. Shift A runs 06:00-14:00 IST, Shift B runs 14:00-22:00 IST.
'
	ai_question_categorization 'This semantic view covers manufacturing OEE analytics, predictive maintenance alerts, asset health monitoring, work orders, downtime analysis, and reliability metrics. Questions about sensor telemetry raw data, training ML models, or approving work orders are outside the scope of this view.'
	ai_verified_queries (
		LOWEST_OEE_ASSET_LAST_7_DAYS AS ( 
QUESTION 'Which asset had the lowest OEE in the last 7 days?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.ASSET_ID,
       SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0) AS availability,
       LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0) AS performance,
       SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0) AS quality,
       (SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0))
       * LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0)
       * (SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0)) AS oee
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.SHIFT_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY o.ASSET_ID ORDER BY oee ASC LIMIT 5
'),
		OEE_BY_LINE_LAST_7_DAYS AS ( 
QUESTION 'What is the OEE for each production line over the last 7 days?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.LINE_ID,
       SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0) AS availability,
       LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0) AS performance,
       SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0) AS quality,
       (SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0))
       * LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0)
       * (SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0)) AS oee
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.SHIFT_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY o.LINE_ID ORDER BY o.LINE_ID
'),
		OEE_TREND_BY_SHIFT AS ( 
QUESTION 'Show the daily OEE trend by shift for LINE_1 in the last 7 days' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.SHIFT_DATE, o.SHIFT_CODE,
       SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0) AS availability,
       LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0) AS performance,
       SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0) AS quality,
       (SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0))
       * LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0)
       * (SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0)) AS oee
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.LINE_ID = ''LINE_1'' AND o.SHIFT_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY o.SHIFT_DATE, o.SHIFT_CODE ORDER BY o.SHIFT_DATE, o.SHIFT_CODE
'),
		AVAILABILITY_BY_ASSET_TODAY AS ( 
QUESTION 'What is the availability for each asset today?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.ASSET_ID,
       SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0) AS availability
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.SHIFT_DATE = CURRENT_DATE() GROUP BY o.ASSET_ID ORDER BY availability ASC
'),
		MOST_DOWNTIME_LINE_THIS_MONTH AS ( 
QUESTION 'Which line has the most unplanned downtime this month?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT a.LINE_ID, SUM(d.MINUTES) AS total_downtime_min FROM AEGIS_OEE.CORE.DOWNTIME_EVENT d JOIN AEGIS_OEE.CORE.ASSET a ON d.ASSET_ID = a.ASSET_ID WHERE d.IS_PLANNED = FALSE
  AND d.START_TS >= DATE_TRUNC(''month'', CURRENT_DATE())
GROUP BY a.LINE_ID ORDER BY total_downtime_min DESC
'),
		REJECT_COUNT_BY_ASSET_LAST_7 AS ( 
QUESTION 'What are the reject counts by asset for the last week?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.ASSET_ID, SUM(o.REJECT_COUNT) AS total_rejects FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.SHIFT_DATE >= DATEADD(''day'', -7, CURRENT_DATE()) GROUP BY o.ASSET_ID ORDER BY total_rejects DESC
'),
		QUALITY_RATE_BY_LINE AS ( 
QUESTION 'What is the quality rate by production line for the last 30 days?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.LINE_ID,
       SUM(o.GOOD_COUNT) AS total_good,
       SUM(o.TOTAL_COUNT) AS total_produced,
       SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0) AS quality_rate
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.SHIFT_DATE >= DATEADD(''day'', -30, CURRENT_DATE()) GROUP BY o.LINE_ID ORDER BY o.LINE_ID
'),
		PERFORMANCE_BY_LINE1_ASSETS AS ( 
QUESTION 'What is the performance rate for LINE_1 assets this week?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.ASSET_ID,
       LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0) AS performance
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o WHERE o.LINE_ID = ''LINE_1'' AND o.SHIFT_DATE >= DATE_TRUNC(''week'', CURRENT_DATE()) GROUP BY o.ASSET_ID ORDER BY performance ASC
'),
		AVERAGE_OEE_BY_SHIFT_CODE AS ( 
QUESTION 'What is the OEE by shift code (A vs B)?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT o.SHIFT_CODE,
       (SUM(o.RUN_MIN) / NULLIF(SUM(o.PLANNED_MIN), 0))
       * LEAST(SUM(o.IDEAL_CYCLE_S * o.TOTAL_COUNT) / NULLIF(SUM(o.RUN_MIN) * 60, 0), 1.0)
       * (SUM(o.GOOD_COUNT) / NULLIF(SUM(o.TOTAL_COUNT), 0)) AS oee
FROM AEGIS_OEE.SEMANTIC.DT_SHIFT_OEE o GROUP BY o.SHIFT_CODE ORDER BY o.SHIFT_CODE
'),
		DOWNTIME_BY_FAILURE_MODE AS ( 
QUESTION 'Which failure mode causes the most downtime?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT d.FAILURE_MODE, SUM(d.MINUTES) AS total_downtime_min, COUNT(*) AS event_count FROM AEGIS_OEE.CORE.DOWNTIME_EVENT d WHERE d.IS_PLANNED = FALSE AND d.FAILURE_MODE IS NOT NULL GROUP BY d.FAILURE_MODE ORDER BY total_downtime_min DESC
'),
		HIGHEST_FAILURE_PROBABILITY_ASSETS AS ( 
QUESTION 'Which assets have the highest failure probability right now?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT h.ASSET_ID, a.ASSET_TYPE, a.LINE_ID, a.CRITICALITY,
       h.HEALTH_SCORE, h.FAILURE_PROBABILITY_24H, h.PREDICTED_MODE, h.RISK_LEVEL
FROM AEGIS_OEE.FEATURES.DT_ASSET_HEALTH h JOIN AEGIS_OEE.CORE.ASSET a ON h.ASSET_ID = a.ASSET_ID ORDER BY h.FAILURE_PROBABILITY_24H DESC LIMIT 5
'),
		OPEN_ALERTS_BY_SEVERITY AS ( 
QUESTION 'How many alerts are open by severity?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT al.SEVERITY, al.STATUS, COUNT(*) AS alert_count FROM AEGIS_OEE.ACTION.ALERT al WHERE al.STATUS NOT IN (''CLOSED'', ''SUPPRESSED'') GROUP BY al.SEVERITY, al.STATUS ORDER BY al.SEVERITY, al.STATUS
'),
		MTBF_MTTR_BY_ASSET_TYPE AS ( 
QUESTION 'What is the MTBF and MTTR for each asset type?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT m.ASSET_TYPE,
       AVG(m.MTBF_MIN) AS avg_mtbf_min,
       AVG(m.MTTR_MIN) AS avg_mttr_min,
       SUM(m.FAILURE_COUNT) AS total_failures
FROM AEGIS_OEE.SEMANTIC.V_MTBF_MTTR m GROUP BY m.ASSET_TYPE ORDER BY avg_mtbf_min ASC
'),
		WORK_ORDERS_BY_STATE AS ( 
QUESTION 'How many work orders are in each state?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT w.STATE, COUNT(*) AS wo_count FROM AEGIS_OEE.ACTION.WORK_ORDER w GROUP BY w.STATE ORDER BY wo_count DESC
'),
		ESTIMATED_OEE_LOSS_FROM_ALERTS AS ( 
QUESTION 'What is the total estimated OEE loss from current alerts?' 
VERIFIED_AT 1788105600
VERIFIED_BY 'SYSTEM'
ONBOARDING_QUESTION false
SQL 'SELECT al.ASSET_ID, al.SEVERITY, al.PREDICTED_MODE,
       al.OEE_IMPACT_EST AS estimated_oee_loss_pct,
       al.FAILURE_PROBABILITY, al.CONFIDENCE
FROM AEGIS_OEE.ACTION.ALERT al WHERE al.STATUS NOT IN (''CLOSED'', ''SUPPRESSED'') ORDER BY al.OEE_IMPACT_EST DESC NULLS LAST
')
	)
	with extension (CA='{"tables":[{"name":"DT_SHIFT_OEE","dimensions":[{"name":"LINE_ID"},{"name":"ASSET_ID"},{"name":"SHIFT_CODE"}],"facts":[{"name":"PLANNED_MIN"},{"name":"DOWNTIME_MIN"},{"name":"RUN_MIN"},{"name":"TOTAL_COUNT"},{"name":"GOOD_COUNT"},{"name":"REJECT_COUNT"},{"name":"IDEAL_CYCLE_S"}],"metrics":[{"name":"TOTAL_PLANNED_MIN"},{"name":"TOTAL_DOWNTIME_MIN"},{"name":"TOTAL_RUN_MIN"},{"name":"TOTAL_PRODUCED"},{"name":"TOTAL_GOOD"},{"name":"TOTAL_REJECTS"},{"name":"AVAILABILITY"},{"name":"PERFORMANCE"},{"name":"QUALITY"},{"name":"OEE"}],"time_dimensions":[{"name":"SHIFT_DATE"}]},{"name":"ASSET","dimensions":[{"name":"ASSET_ID"},{"name":"LINE_ID"},{"name":"SITE_ID"},{"name":"ASSET_TYPE"},{"name":"MANUFACTURER"},{"name":"CRITICALITY"}],"facts":[{"name":"IDEAL_RPM"},{"name":"TEMP_LIMIT_C"},{"name":"VIB_ALERT_MM_S"},{"name":"VIB_DANGER_MM_S"}],"time_dimensions":[{"name":"INSTALL_DATE"}]},{"name":"DOWNTIME_EVENT","dimensions":[{"name":"EVENT_ID"},{"name":"DT_ASSET_ID"},{"name":"IS_PLANNED"},{"name":"REASON_CODE"},{"name":"FAILURE_MODE"}],"facts":[{"name":"DOWNTIME_MINUTES"}],"metrics":[{"name":"TOTAL_DOWNTIME_EVENTS"},{"name":"SUM_DOWNTIME_MINUTES"}],"time_dimensions":[{"name":"START_TS"},{"name":"END_TS"}]},{"name":"PRODUCTION_ORDER","dimensions":[{"name":"ORDER_ID"},{"name":"PO_LINE_ID"},{"name":"PRODUCT_CODE"}],"facts":[{"name":"PLANNED_QTY"}],"time_dimensions":[{"name":"PLANNED_START_TS"},{"name":"PLANNED_END_TS"}]},{"name":"ALERT","dimensions":[{"name":"ALERT_ID"},{"name":"ALERT_ASSET_ID"},{"name":"SEVERITY"},{"name":"PREDICTED_MODE"},{"name":"ALERT_STATUS"}],"facts":[{"name":"CONFIDENCE"},{"name":"FAILURE_PROBABILITY"},{"name":"OEE_IMPACT_EST"}],"metrics":[{"name":"ALERT_COUNT"},{"name":"TOTAL_OEE_IMPACT"}],"time_dimensions":[{"name":"ONSET_TS"}]},{"name":"WORK_ORDER","dimensions":[{"name":"WO_ID"},{"name":"WO_ALERT_ID"},{"name":"WO_ASSET_ID"},{"name":"WO_PRIORITY"},{"name":"WO_STATE"},{"name":"WO_TITLE"}],"metrics":[{"name":"WO_COUNT"}],"time_dimensions":[{"name":"APPROVED_TS"}]},{"name":"DT_ASSET_HEALTH","dimensions":[{"name":"HEALTH_ASSET_ID"},{"name":"PREDICTED_FAILURE_MODE"},{"name":"RISK_LEVEL"}],"facts":[{"name":"HEALTH_SCORE"},{"name":"ANOMALY_DISTANCE"},{"name":"FAILURE_PROBABILITY_24H"}],"time_dimensions":[{"name":"LAST_READING_TS"}]},{"name":"V_MTBF_MTTR","dimensions":[{"name":"MTBF_ASSET_ID"},{"name":"MTBF_ASSET_TYPE"},{"name":"MTBF_LINE_ID"}],"facts":[{"name":"FAILURE_COUNT"},{"name":"TOTAL_UNPLANNED_DOWNTIME_MIN"},{"name":"TOTAL_RUN_MIN_MTBF"},{"name":"MTBF_MIN"},{"name":"MTTR_MIN"}]}],"relationships":[{"name":"oee_to_asset"},{"name":"downtime_to_asset"},{"name":"alert_to_asset"},{"name":"wo_to_alert"},{"name":"wo_to_asset"},{"name":"health_to_asset"},{"name":"mtbf_to_asset"}]}');

-- ── Load maintenance docs into SEMANTIC.MAINTENANCE_DOCS ──
-- The docs are loaded from data_gen/docs/ via load_data.sh (step 03).
-- They should already be in SEMANTIC.MAINTENANCE_DOCS by this point.

-- ── Cortex Search Service ──

create or replace cortex search service MAINTENANCE_SEARCH
	ON CONTENT
	attributes ASSET_ID,DOC_TYPE
	warehouse='AEGIS_WH'
	target_lag='1 hour'
	refresh_mode=INCREMENTAL
	as (
        SELECT
            DOC_ID,
            ASSET_ID,
            DOC_TYPE,
            TITLE,
            CONTENT,
            SOURCE
        FROM AEGIS_OEE.SEMANTIC.MAINTENANCE_DOCS
    );
