-- =============================================================
-- Mission 00 — AegisOEE Foundation DDL
-- Idempotent: safe to re-run at any time.
-- =============================================================

-- Database
CREATE DATABASE IF NOT EXISTS AEGIS_OEE;

-- Schemas
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.RAW;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.CORE;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.FEATURES;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.ML;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.SEMANTIC;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.ACTION;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.APP;
CREATE SCHEMA IF NOT EXISTS AEGIS_OEE.TEST;

-- Warehouses
CREATE WAREHOUSE IF NOT EXISTS AEGIS_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS AEGIS_APP_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Stages
CREATE STAGE IF NOT EXISTS AEGIS_OEE.RAW.DOC_STAGE
  DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS AEGIS_OEE.APP.APP_STAGE;

CREATE STAGE IF NOT EXISTS AEGIS_OEE.APP.SKILL_STAGE;

-- Env probes table
CREATE TABLE IF NOT EXISTS AEGIS_OEE.TEST.ENV_PROBES (
  probe_name  STRING,
  result      STRING,
  detail      STRING,
  probed_at   TIMESTAMP_TZ
);
