-- =============================================================
-- Mission 03 — Hybrid ML: Anomaly Detection, Forecasts, Z-Score
-- Fallback, and Risk Fusion.
-- Idempotent: safe to re-run (models will retrain).
-- =============================================================

USE DATABASE AEGIS_OEE;
USE WAREHOUSE AEGIS_WH;

-- =============================================================
-- PART A: Anomaly Detection Models (3 signal families)
-- Training: healthy-only data from first 30 days (before 2026-07-15)
-- Scoring: data from 2026-07-15 onward
-- 5-min aggregated to reduce training volume while preserving
-- time-series structure.
-- =============================================================

-- Training views: exclude ground-truth degradation spans (date-range
-- exclusion only, NO labels leak into features).
CREATE OR REPLACE VIEW ML.V_TRAIN_VIB_HEALTHY AS
SELECT
  s.ASSET_ID,
  TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
  AVG(s.VIB_RMS_MEAN) AS VIB_RMS_MEAN
FROM FEATURES.DT_SENSOR_1MIN s
WHERE s.VIB_RMS_MEAN IS NOT NULL
  AND s.MINUTE_TS < '2026-07-15'::TIMESTAMP_TZ
  AND NOT EXISTS (
    SELECT 1 FROM TEST.GROUND_TRUTH_FAILURES g
    WHERE g.ASSET_ID = s.ASSET_ID
      AND s.MINUTE_TS >= g.DEGRADATION_START_TS
      AND s.MINUTE_TS <= g.FAILURE_TS
  )
GROUP BY s.ASSET_ID, TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

CREATE OR REPLACE VIEW ML.V_TRAIN_TEMP_HEALTHY AS
SELECT
  s.ASSET_ID,
  TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
  AVG(s.TEMP_C_MEAN) AS TEMP_C_MEAN
FROM FEATURES.DT_SENSOR_1MIN s
WHERE s.TEMP_C_MEAN IS NOT NULL
  AND s.MINUTE_TS < '2026-07-15'::TIMESTAMP_TZ
  AND NOT EXISTS (
    SELECT 1 FROM TEST.GROUND_TRUTH_FAILURES g
    WHERE g.ASSET_ID = s.ASSET_ID
      AND s.MINUTE_TS >= g.DEGRADATION_START_TS
      AND s.MINUTE_TS <= g.FAILURE_TS
  )
GROUP BY s.ASSET_ID, TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

CREATE OR REPLACE VIEW ML.V_TRAIN_RPM_HEALTHY AS
SELECT
  s.ASSET_ID,
  TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
  AVG(s.RPM_MEAN) AS RPM_MEAN
FROM FEATURES.DT_SENSOR_1MIN s
WHERE s.RPM_MEAN IS NOT NULL
  AND s.MINUTE_TS < '2026-07-15'::TIMESTAMP_TZ
  AND NOT EXISTS (
    SELECT 1 FROM TEST.GROUND_TRUTH_FAILURES g
    WHERE g.ASSET_ID = s.ASSET_ID
      AND s.MINUTE_TS >= g.DEGRADATION_START_TS
      AND s.MINUTE_TS <= g.FAILURE_TS
  )
GROUP BY s.ASSET_ID, TIME_SLICE(s.MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

-- Train models (~55K rows per signal, 10 series)
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.AD_VIBRATION(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.V_TRAIN_VIB_HEALTHY'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'MINUTE_TS',
  TARGET_COLNAME => 'VIB_RMS_MEAN',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.AD_TEMPERATURE(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.V_TRAIN_TEMP_HEALTHY'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'MINUTE_TS',
  TARGET_COLNAME => 'TEMP_C_MEAN',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.AD_RPM(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.V_TRAIN_RPM_HEALTHY'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'MINUTE_TS',
  TARGET_COLNAME => 'RPM_MEAN',
  LABEL_COLNAME => ''
);

-- =============================================================
-- PART B: Scoring Procedure + Task
-- Output columns from DETECT_ANOMALIES: SERIES, TS, Y, FORECAST,
-- LOWER_BOUND, UPPER_BOUND, IS_ANOMALY, PERCENTILE, DISTANCE
-- =============================================================

CREATE OR REPLACE PROCEDURE ML.DETECT_ANOMALIES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_VIB AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(VIB_RMS_MEAN) AS VIB_RMS_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE MINUTE_TS >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    AND VIB_RMS_MEAN IS NOT NULL
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_VIB_RESULTS AS
  SELECT * FROM TABLE(
    ML.AD_VIBRATION!DETECT_ANOMALIES(
      INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_VIB'),
      SERIES_COLNAME => 'ASSET_ID',
      TIMESTAMP_COLNAME => 'MINUTE_TS',
      TARGET_COLNAME => 'VIB_RMS_MEAN'
    )
  );

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_TEMP AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(TEMP_C_MEAN) AS TEMP_C_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE MINUTE_TS >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    AND TEMP_C_MEAN IS NOT NULL
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_TEMP_RESULTS AS
  SELECT * FROM TABLE(
    ML.AD_TEMPERATURE!DETECT_ANOMALIES(
      INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_TEMP'),
      SERIES_COLNAME => 'ASSET_ID',
      TIMESTAMP_COLNAME => 'MINUTE_TS',
      TARGET_COLNAME => 'TEMP_C_MEAN'
    )
  );

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_RPM AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(RPM_MEAN) AS RPM_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE MINUTE_TS >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    AND RPM_MEAN IS NOT NULL
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_RPM_RESULTS AS
  SELECT * FROM TABLE(
    ML.AD_RPM!DETECT_ANOMALIES(
      INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_RPM'),
      SERIES_COLNAME => 'ASSET_ID',
      TIMESTAMP_COLNAME => 'MINUTE_TS',
      TARGET_COLNAME => 'RPM_MEAN'
    )
  );

  MERGE INTO ML.ANOMALY_EVENTS tgt
  USING (
    SELECT SERIES AS ASSET_ID, TS::TIMESTAMP_TZ AS TS, 'vibration_rms' AS SERIES_NAME,
           IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND AS LOWER, UPPER_BOUND AS UPPER
    FROM ML.TMP_VIB_RESULTS
    UNION ALL
    SELECT SERIES, TS::TIMESTAMP_TZ, 'temp_c',
           IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND, UPPER_BOUND
    FROM ML.TMP_TEMP_RESULTS
    UNION ALL
    SELECT SERIES, TS::TIMESTAMP_TZ, 'rpm',
           IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND, UPPER_BOUND
    FROM ML.TMP_RPM_RESULTS
  ) src
  ON tgt.ASSET_ID = src.ASSET_ID AND tgt.TS = src.TS AND tgt.SERIES_NAME = src.SERIES_NAME
  WHEN MATCHED THEN UPDATE SET
    IS_ANOMALY = src.IS_ANOMALY, DISTANCE = src.DISTANCE,
    PERCENTILE = src.PERCENTILE, FORECAST = src.FORECAST,
    LOWER = src.LOWER, UPPER = src.UPPER
  WHEN NOT MATCHED THEN INSERT VALUES
    (src.ASSET_ID, src.TS, src.SERIES_NAME, src.IS_ANOMALY, src.DISTANCE,
     src.PERCENTILE, src.FORECAST, src.LOWER, src.UPPER);

  RETURN 'DETECT_ANOMALIES complete';
END;

CREATE OR REPLACE TASK ML.TASK_DETECT_ANOMALIES
  WAREHOUSE = AEGIS_WH
  SCHEDULE  = '5 MINUTE'
AS
  CALL ML.DETECT_ANOMALIES();

-- =============================================================
-- PART C: Forecast Models
-- =============================================================

CREATE OR REPLACE VIEW ML.V_VIB_HOURLY AS
SELECT
  ASSET_ID,
  DATE_TRUNC('HOUR', MINUTE_TS)::TIMESTAMP_NTZ AS HOUR_TS,
  AVG(VIB_RMS_MEAN) AS VIB_RMS_MEAN
FROM FEATURES.DT_SENSOR_1MIN
WHERE VIB_RMS_MEAN IS NOT NULL
GROUP BY ASSET_ID, DATE_TRUNC('HOUR', MINUTE_TS);

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.FC_VIBRATION_HOURLY(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.V_VIB_HOURLY'),
  SERIES_COLNAME => 'ASSET_ID',
  TIMESTAMP_COLNAME => 'HOUR_TS',
  TARGET_COLNAME => 'VIB_RMS_MEAN'
);

CREATE OR REPLACE VIEW ML.V_OEE_DAILY AS
SELECT
  LINE_ID,
  SHIFT_DATE::TIMESTAMP_NTZ AS DAY_TS,
  AVG(OEE)::FLOAT AS OEE_AVG
FROM SEMANTIC.DT_SHIFT_OEE
GROUP BY LINE_ID, SHIFT_DATE;

CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.FC_OEE_DAILY(
  INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'ML.V_OEE_DAILY'),
  SERIES_COLNAME => 'LINE_ID',
  TIMESTAMP_COLNAME => 'DAY_TS',
  TARGET_COLNAME => 'OEE_AVG'
);

CREATE OR REPLACE TABLE ML.SIGNAL_FORECASTS (
  SERIES_TYPE   STRING    NOT NULL,
  SERIES_ID     STRING    NOT NULL,
  TS            TIMESTAMP_NTZ NOT NULL,
  FORECAST      FLOAT,
  LOWER_BOUND   FLOAT,
  UPPER_BOUND   FLOAT,
  GENERATED_AT  TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

INSERT OVERWRITE INTO ML.SIGNAL_FORECASTS
SELECT 'vibration_rms', SERIES, TS, FORECAST, LOWER_BOUND, UPPER_BOUND, CURRENT_TIMESTAMP()
FROM TABLE(ML.FC_VIBRATION_HOURLY!FORECAST(FORECASTING_PERIODS => 24));

INSERT INTO ML.SIGNAL_FORECASTS
SELECT 'oee_daily', SERIES, TS, FORECAST, LOWER_BOUND, UPPER_BOUND, CURRENT_TIMESTAMP()
FROM TABLE(ML.FC_OEE_DAILY!FORECAST(FORECASTING_PERIODS => 7));

-- =============================================================
-- PART D: Z-Score Fallback Detector
-- Flags anomalies when |z-score| > 2.5 for 3+ consecutive
-- 15-min windows. Writes to same ANOMALY_EVENTS format.
-- =============================================================

CREATE OR REPLACE PROCEDURE ML.DETECT_ZSCORE_ANOMALIES()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
  MERGE INTO ML.ANOMALY_EVENTS tgt
  USING (
    WITH scored AS (
      SELECT ASSET_ID, WINDOW_TS, VIB_RMS_ZSCORE, TEMP_C_ZSCORE, RPM_ZSCORE,
        LAG(VIB_RMS_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS vib_z_lag1,
        LAG(VIB_RMS_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS vib_z_lag2,
        LAG(TEMP_C_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS temp_z_lag1,
        LAG(TEMP_C_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS temp_z_lag2,
        LAG(RPM_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS rpm_z_lag1,
        LAG(RPM_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS rpm_z_lag2
      FROM FEATURES.DT_SENSOR_FEATURES_15MIN
      WHERE WINDOW_TS >= DATEADD('HOUR', -24, CURRENT_TIMESTAMP())
    )
    SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ AS TS, 'zscore_vibration' AS SERIES_NAME,
           TRUE AS IS_ANOMALY, ABS(VIB_RMS_ZSCORE) AS DISTANCE,
           NULL::FLOAT AS PERCENTILE, NULL::FLOAT AS FORECAST, NULL::FLOAT AS LOWER, NULL::FLOAT AS UPPER
    FROM scored WHERE ABS(VIB_RMS_ZSCORE) > 2.5 AND ABS(vib_z_lag1) > 2.5 AND ABS(vib_z_lag2) > 2.5
    UNION ALL
    SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ, 'zscore_temp', TRUE, ABS(TEMP_C_ZSCORE),
           NULL, NULL, NULL, NULL
    FROM scored WHERE ABS(TEMP_C_ZSCORE) > 2.5 AND ABS(temp_z_lag1) > 2.5 AND ABS(temp_z_lag2) > 2.5
    UNION ALL
    SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ, 'zscore_rpm', TRUE, ABS(RPM_ZSCORE),
           NULL, NULL, NULL, NULL
    FROM scored WHERE ABS(RPM_ZSCORE) > 2.5 AND ABS(rpm_z_lag1) > 2.5 AND ABS(rpm_z_lag2) > 2.5
  ) src
  ON tgt.ASSET_ID = src.ASSET_ID AND tgt.TS = src.TS AND tgt.SERIES_NAME = src.SERIES_NAME
  WHEN MATCHED THEN UPDATE SET IS_ANOMALY = src.IS_ANOMALY, DISTANCE = src.DISTANCE
  WHEN NOT MATCHED THEN INSERT VALUES
    (src.ASSET_ID, src.TS, src.SERIES_NAME, src.IS_ANOMALY, src.DISTANCE,
     src.PERCENTILE, src.FORECAST, src.LOWER, src.UPPER);

  RETURN 'Z-score anomaly detection complete';
END;

-- =============================================================
-- PART E: Backfill procedures (historical scoring)
-- =============================================================

CREATE OR REPLACE PROCEDURE ML.DETECT_ANOMALIES_BACKFILL()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_VIB AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(VIB_RMS_MEAN) AS VIB_RMS_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE VIB_RMS_MEAN IS NOT NULL AND MINUTE_TS >= '2026-07-15'::TIMESTAMP_TZ
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_VIB_RESULTS AS
  SELECT * FROM TABLE(ML.AD_VIBRATION!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_VIB'),
    SERIES_COLNAME => 'ASSET_ID', TIMESTAMP_COLNAME => 'MINUTE_TS', TARGET_COLNAME => 'VIB_RMS_MEAN'));

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_TEMP AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(TEMP_C_MEAN) AS TEMP_C_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE TEMP_C_MEAN IS NOT NULL AND MINUTE_TS >= '2026-07-15'::TIMESTAMP_TZ
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_TEMP_RESULTS AS
  SELECT * FROM TABLE(ML.AD_TEMPERATURE!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_TEMP'),
    SERIES_COLNAME => 'ASSET_ID', TIMESTAMP_COLNAME => 'MINUTE_TS', TARGET_COLNAME => 'TEMP_C_MEAN'));

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_SCORE_RPM AS
  SELECT ASSET_ID,
         TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START') AS MINUTE_TS,
         AVG(RPM_MEAN) AS RPM_MEAN
  FROM FEATURES.DT_SENSOR_1MIN
  WHERE RPM_MEAN IS NOT NULL AND MINUTE_TS >= '2026-07-15'::TIMESTAMP_TZ
  GROUP BY ASSET_ID, TIME_SLICE(MINUTE_TS::TIMESTAMP_NTZ, 5, 'MINUTE', 'START');

  CREATE OR REPLACE TEMPORARY TABLE ML.TMP_RPM_RESULTS AS
  SELECT * FROM TABLE(ML.AD_RPM!DETECT_ANOMALIES(
    INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'ML.TMP_SCORE_RPM'),
    SERIES_COLNAME => 'ASSET_ID', TIMESTAMP_COLNAME => 'MINUTE_TS', TARGET_COLNAME => 'RPM_MEAN'));

  DELETE FROM ML.ANOMALY_EVENTS WHERE SERIES_NAME IN ('vibration_rms','temp_c','rpm');

  INSERT INTO ML.ANOMALY_EVENTS (ASSET_ID, TS, SERIES_NAME, IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER, UPPER)
  SELECT SERIES, TS::TIMESTAMP_TZ, 'vibration_rms', IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND, UPPER_BOUND
  FROM ML.TMP_VIB_RESULTS
  UNION ALL
  SELECT SERIES, TS::TIMESTAMP_TZ, 'temp_c', IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND, UPPER_BOUND
  FROM ML.TMP_TEMP_RESULTS
  UNION ALL
  SELECT SERIES, TS::TIMESTAMP_TZ, 'rpm', IS_ANOMALY, DISTANCE, PERCENTILE, FORECAST, LOWER_BOUND, UPPER_BOUND
  FROM ML.TMP_RPM_RESULTS;

  RETURN 'Backfill anomaly scoring complete';
END;

CREATE OR REPLACE PROCEDURE ML.DETECT_ZSCORE_ANOMALIES_BACKFILL()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
BEGIN
  DELETE FROM ML.ANOMALY_EVENTS WHERE SERIES_NAME LIKE 'zscore_%';

  INSERT INTO ML.ANOMALY_EVENTS
  WITH scored AS (
    SELECT ASSET_ID, WINDOW_TS, VIB_RMS_ZSCORE, TEMP_C_ZSCORE, RPM_ZSCORE,
      LAG(VIB_RMS_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS vib_z_lag1,
      LAG(VIB_RMS_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS vib_z_lag2,
      LAG(TEMP_C_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS temp_z_lag1,
      LAG(TEMP_C_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS temp_z_lag2,
      LAG(RPM_ZSCORE, 1) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS rpm_z_lag1,
      LAG(RPM_ZSCORE, 2) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_TS) AS rpm_z_lag2
    FROM FEATURES.DT_SENSOR_FEATURES_15MIN
  )
  SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ, 'zscore_vibration', TRUE,
         ABS(VIB_RMS_ZSCORE), NULL, NULL, NULL, NULL
  FROM scored WHERE ABS(VIB_RMS_ZSCORE) > 2.5 AND ABS(vib_z_lag1) > 2.5 AND ABS(vib_z_lag2) > 2.5
  UNION ALL
  SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ, 'zscore_temp', TRUE,
         ABS(TEMP_C_ZSCORE), NULL, NULL, NULL, NULL
  FROM scored WHERE ABS(TEMP_C_ZSCORE) > 2.5 AND ABS(temp_z_lag1) > 2.5 AND ABS(temp_z_lag2) > 2.5
  UNION ALL
  SELECT ASSET_ID, WINDOW_TS::TIMESTAMP_TZ, 'zscore_rpm', TRUE,
         ABS(RPM_ZSCORE), NULL, NULL, NULL, NULL
  FROM scored WHERE ABS(RPM_ZSCORE) > 2.5 AND ABS(rpm_z_lag1) > 2.5 AND ABS(rpm_z_lag2) > 2.5;

  RETURN 'Z-score backfill complete';
END;

-- =============================================================
-- PART F: Risk Fusion — DT_ASSET_HEALTH v2
-- Fuses rule-based health, ML anomaly distance, z-score
-- persistence, and asset criticality.
-- =============================================================

CREATE OR REPLACE DYNAMIC TABLE FEATURES.DT_ASSET_HEALTH
  TARGET_LAG = '5 minutes'
  WAREHOUSE = AEGIS_WH
AS
WITH latest_ts AS (
  SELECT asset_id, MAX(window_ts) AS max_window_ts
  FROM FEATURES.DT_SENSOR_FEATURES_15MIN
  GROUP BY asset_id
),
latest_features AS (
  SELECT f.*
  FROM FEATURES.DT_SENSOR_FEATURES_15MIN f
  JOIN latest_ts lt ON f.asset_id = lt.asset_id AND f.window_ts = lt.max_window_ts
),
recent_downtime AS (
  SELECT asset_id, SUM(minutes) AS recent_down_min
  FROM CORE.DOWNTIME_EVENT
  WHERE is_planned = FALSE AND end_ts >= DATEADD('DAY', -7, CURRENT_TIMESTAMP())
  GROUP BY asset_id
),
rule_scored AS (
  SELECT
    lf.asset_id, lf.window_ts AS last_reading_ts, a.criticality,
    lf.vib_rms_zscore, lf.temp_c_zscore, lf.rpm_zscore,
    GREATEST(0, LEAST(100,
      100
      - CASE WHEN lf.vib_rms_mean >= a.vib_danger_mm_s THEN 40
             WHEN lf.vib_rms_mean >= a.vib_alert_mm_s  THEN 20 + 20 * LEAST(1.0,
                   (lf.vib_rms_mean - a.vib_alert_mm_s) / NULLIF(a.vib_danger_mm_s - a.vib_alert_mm_s, 0))
             WHEN lf.vib_rms_mean >= a.vib_alert_mm_s * 0.8 THEN 10 ELSE 0 END
      - CASE WHEN lf.temp_c_mean >= a.temp_limit_c       THEN 25
             WHEN lf.temp_c_mean >= a.temp_limit_c * 0.9 THEN 15
             WHEN lf.temp_c_mean >= a.temp_limit_c * 0.8 THEN 5 ELSE 0 END
      - CASE WHEN ABS(COALESCE(lf.vib_rms_zscore, 0)) > 3   THEN 15
             WHEN ABS(COALESCE(lf.vib_rms_zscore, 0)) > 2   THEN 10
             WHEN ABS(COALESCE(lf.vib_rms_zscore, 0)) > 1.5 THEN 5 ELSE 0 END
      - CASE WHEN COALESCE(rd.recent_down_min, 0) > 480 THEN 10
             WHEN COALESCE(rd.recent_down_min, 0) > 120 THEN 5 ELSE 0 END
      - CASE WHEN COALESCE(lf.rpm_variance, 0) > 10000 THEN 10
             WHEN COALESCE(lf.rpm_variance, 0) > 5000  THEN 5 ELSE 0 END
    )) AS rule_health_score
  FROM latest_features lf
  JOIN CORE.ASSET a ON lf.asset_id = a.asset_id
  LEFT JOIN recent_downtime rd ON lf.asset_id = rd.asset_id
),
anomaly_evidence AS (
  SELECT ASSET_ID,
    MAX(CASE WHEN SERIES_NAME = 'vibration_rms' AND IS_ANOMALY THEN DISTANCE ELSE 0 END) AS vib_anomaly_dist,
    MAX(CASE WHEN SERIES_NAME = 'temp_c'        AND IS_ANOMALY THEN DISTANCE ELSE 0 END) AS temp_anomaly_dist,
    MAX(CASE WHEN SERIES_NAME = 'rpm'           AND IS_ANOMALY THEN DISTANCE ELSE 0 END) AS rpm_anomaly_dist,
    COUNT(CASE WHEN IS_ANOMALY THEN 1 END) AS anomaly_count_6h
  FROM ML.ANOMALY_EVENTS
  WHERE TS >= DATEADD('HOUR', -6, CURRENT_TIMESTAMP())
  GROUP BY ASSET_ID
),
fused AS (
  SELECT rs.asset_id, rs.last_reading_ts, rs.criticality, rs.rule_health_score,
    GREATEST(COALESCE(ae.vib_anomaly_dist,0), COALESCE(ae.temp_anomaly_dist,0), COALESCE(ae.rpm_anomaly_dist,0)) AS max_anomaly_distance,
    GREATEST(ABS(COALESCE(rs.vib_rms_zscore,0)), ABS(COALESCE(rs.temp_c_zscore,0)), ABS(COALESCE(rs.rpm_zscore,0))) AS max_zscore,
    COALESCE(ae.anomaly_count_6h, 0) AS anomaly_count_6h,
    CASE
      WHEN GREATEST(COALESCE(ae.vib_anomaly_dist,0), COALESCE(ae.temp_anomaly_dist,0), COALESCE(ae.rpm_anomaly_dist,0)) = 0 THEN NULL
      WHEN COALESCE(ae.vib_anomaly_dist,0) >= COALESCE(ae.temp_anomaly_dist,0)
        AND COALESCE(ae.vib_anomaly_dist,0) >= COALESCE(ae.rpm_anomaly_dist,0) THEN 'BEARING_WEAR'
      WHEN COALESCE(ae.temp_anomaly_dist,0) >= COALESCE(ae.rpm_anomaly_dist,0) THEN 'COOLING_RESTRICTION'
      ELSE 'RPM_INSTABILITY'
    END AS predicted_mode
  FROM rule_scored rs
  LEFT JOIN anomaly_evidence ae ON rs.asset_id = ae.ASSET_ID
)
SELECT
  asset_id, last_reading_ts,
  GREATEST(0, LEAST(100,
    rule_health_score - LEAST(20, max_anomaly_distance * 5)
    - CASE WHEN anomaly_count_6h > 10 THEN 10 WHEN anomaly_count_6h > 5 THEN 5 ELSE 0 END
  ))::FLOAT AS health_score,
  max_anomaly_distance::FLOAT AS anomaly_distance,
  LEAST(1.0, GREATEST(0,
    (max_anomaly_distance / 10.0) * 0.4
    + (LEAST(max_zscore, 5.0) / 5.0) * 0.3
    + (anomaly_count_6h / 50.0) * 0.2
    + (criticality / 5.0) * 0.1
  ))::FLOAT AS failure_probability_24h,
  predicted_mode,
  CASE
    WHEN GREATEST(0, LEAST(100, rule_health_score - LEAST(20, max_anomaly_distance * 5)
           - CASE WHEN anomaly_count_6h > 10 THEN 10 WHEN anomaly_count_6h > 5 THEN 5 ELSE 0 END)) <= 30 THEN 'CRITICAL'
    WHEN GREATEST(0, LEAST(100, rule_health_score - LEAST(20, max_anomaly_distance * 5)
           - CASE WHEN anomaly_count_6h > 10 THEN 10 WHEN anomaly_count_6h > 5 THEN 5 ELSE 0 END)) <= 50 THEN 'HIGH'
    WHEN GREATEST(0, LEAST(100, rule_health_score - LEAST(20, max_anomaly_distance * 5)
           - CASE WHEN anomaly_count_6h > 10 THEN 10 WHEN anomaly_count_6h > 5 THEN 5 ELSE 0 END)) <= 70 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS risk_level
FROM fused;

-- Resume scoring task
ALTER TASK ML.TASK_DETECT_ANOMALIES RESUME;
